/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 12 -standalone -fma -generic-arith -compact -name dft_codelet_r2hc_12 */

/*
 * This function contains 38 FP additions, 10 FP multiplications,
 * (or, 30 additions, 2 multiplications, 8 fused multiply/add),
 * 21 stack variables, 2 constants, and 24 memory accesses
 */
void dft_codelet_r2hc_12(const R * R0, const R * R1, R * Cr, R * Ci)
{
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  {
    
    {
      E T5, Tp, Tm, Tk, Ty, Tt, Ta, Tq, Tn, Tf, Tz, Tu, Tl, To;
      {
        E T1, T2, T3, T4;
        T1 = R0[0];
        T2 = R0[WSR(2)];
        T3 = R0[WSR(4)];
        T4 = ADD(T2, T3);
        T5 = ADD(T1, T4);
        Tp = FNMS(KP500000000, T4, T1);
        Tm = SUB(T3, T2);
      }
      {
        E Tg, Th, Ti, Tj;
        Tg = R1[WSR(1)];
        Th = R1[WSR(3)];
        Ti = R1[WSR(5)];
        Tj = ADD(Th, Ti);
        Tk = FNMS(KP500000000, Tj, Tg);
        Ty = SUB(Ti, Th);
        Tt = ADD(Tg, Tj);
      }
      {
        E T6, T7, T8, T9;
        T6 = R0[WSR(3)];
        T7 = R0[WSR(5)];
        T8 = R0[WSR(1)];
        T9 = ADD(T7, T8);
        Ta = ADD(T6, T9);
        Tq = FNMS(KP500000000, T9, T6);
        Tn = SUB(T8, T7);
      }
      {
        E Tb, Tc, Td, Te;
        Tb = R1[WSR(4)];
        Tc = R1[0];
        Td = R1[WSR(2)];
        Te = ADD(Tc, Td);
        Tf = FNMS(KP500000000, Te, Tb);
        Tz = SUB(Td, Tc);
        Tu = ADD(Tb, Te);
      }
      Cr[WSCR(3)] = SUB(T5, Ta);
      Ci[WSCI(3)] = SUB(Tt, Tu);
      Tl = SUB(Tf, Tk);
      To = SUB(Tm, Tn);
      Ci[WSCI(1)] = FMA(KP866025403, To, Tl);
      Ci[WSCI(5)] = FNMS(KP866025403, To, Tl);
      {
        E Tx, TA, Tv, Tw;
        Tx = SUB(Tp, Tq);
        TA = SUB(Ty, Tz);
        Cr[WSCR(5)] = FNMS(KP866025403, TA, Tx);
        Cr[WSCR(1)] = FMA(KP866025403, TA, Tx);
        Tv = ADD(T5, Ta);
        Tw = ADD(Tt, Tu);
        Cr[WSCR(6)] = SUB(Tv, Tw);
        Cr[0] = ADD(Tv, Tw);
      }
      {
        E Tr, Ts, TB, TC;
        Tr = ADD(Tp, Tq);
        Ts = ADD(Tk, Tf);
        Cr[WSCR(2)] = SUB(Tr, Ts);
        Cr[WSCR(4)] = ADD(Tr, Ts);
        TB = ADD(Ty, Tz);
        TC = ADD(Tm, Tn);
        Ci[WSCI(2)] = MUL(KP866025403, SUB(TB, TC));
        Ci[WSCI(4)] = MUL(KP866025403, ADD(TC, TB));
      }
    }
  }
}
