/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 12 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_12 */

/*
 * This function contains 38 FP additions, 16 FP multiplications,
 * (or, 22 additions, 0 multiplications, 16 fused multiply/add),
 * 25 stack variables, 2 constants, and 24 memory accesses
 */
void dft_codelet_hc2r_12(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T8, Tb, Tk, Tz, Tu, Tv, Tn, Ty, T3, Tp, Tf, T6, Tq, Ti;
      {
        E T9, Ta, Tl, Tm;
        T8 = Cr[WSCR(3)];
        T9 = Cr[WSCR(5)];
        Ta = Cr[WSCR(1)];
        Tb = ADD(T9, Ta);
        Tk = FNMS(KP2_000000000, T8, Tb);
        Tz = SUB(T9, Ta);
        Tu = Ci[WSCI(3)];
        Tl = Ci[WSCI(5)];
        Tm = Ci[WSCI(1)];
        Tv = ADD(Tl, Tm);
        Tn = SUB(Tl, Tm);
        Ty = FMA(KP2_000000000, Tu, Tv);
      }
      {
        E Te, T1, T2, Td;
        Te = Ci[WSCI(4)];
        T1 = Cr[0];
        T2 = Cr[WSCR(4)];
        Td = SUB(T1, T2);
        T3 = FMA(KP2_000000000, T2, T1);
        Tp = FNMS(KP1_732050807, Te, Td);
        Tf = FMA(KP1_732050807, Te, Td);
      }
      {
        E Th, T4, T5, Tg;
        Th = Ci[WSCI(2)];
        T4 = Cr[WSCR(6)];
        T5 = Cr[WSCR(2)];
        Tg = SUB(T4, T5);
        T6 = FMA(KP2_000000000, T5, T4);
        Tq = FMA(KP1_732050807, Th, Tg);
        Ti = FNMS(KP1_732050807, Th, Tg);
      }
      {
        E T7, Tc, Tx, TA;
        T7 = ADD(T3, T6);
        Tc = ADD(T8, Tb);
        R0[WSR(3)] = FNMS(KP2_000000000, Tc, T7);
        R0[0] = FMA(KP2_000000000, Tc, T7);
        {
          E Tj, To, TB, TC;
          Tj = ADD(Tf, Ti);
          To = FMA(KP1_732050807, Tn, Tk);
          R0[WSR(1)] = ADD(Tj, To);
          R0[WSR(4)] = SUB(Tj, To);
          TB = SUB(Tf, Ti);
          TC = FNMS(KP1_732050807, Tz, Ty);
          R1[WSR(2)] = SUB(TB, TC);
          R1[WSR(5)] = ADD(TB, TC);
        }
        Tx = SUB(Tp, Tq);
        TA = FMA(KP1_732050807, Tz, Ty);
        R1[0] = SUB(Tx, TA);
        R1[WSR(3)] = ADD(Tx, TA);
        {
          E Tt, Tw, Tr, Ts;
          Tt = SUB(T3, T6);
          Tw = SUB(Tu, Tv);
          R1[WSR(4)] = FNMS(KP2_000000000, Tw, Tt);
          R1[WSR(1)] = FMA(KP2_000000000, Tw, Tt);
          Tr = ADD(Tp, Tq);
          Ts = FNMS(KP1_732050807, Tn, Tk);
          R0[WSR(5)] = ADD(Tr, Ts);
          R0[WSR(2)] = SUB(Tr, Ts);
        }
      }
    }
  }
}
