/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 2 -standalone -fma -generic-arith -compact -name dft_codelet_r2hc_2 */

/*
 * This function contains 2 FP additions, 0 FP multiplications,
 * (or, 2 additions, 0 multiplications, 0 fused multiply/add),
 * 3 stack variables, 0 constants, and 4 memory accesses
 */
void dft_codelet_r2hc_2(const R * R0, const R * R1, R * Cr, R * Ci)
{
  {
    
    {
      E T1, T2;
      T1 = R0[0];
      T2 = R1[0];
      Cr[WSCR(1)] = SUB(T1, T2);
      Cr[0] = ADD(T1, T2);
    }
  }
}
