/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 2 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_2 */

/*
 * This function contains 2 FP additions, 0 FP multiplications,
 * (or, 2 additions, 0 multiplications, 0 fused multiply/add),
 * 3 stack variables, 0 constants, and 4 memory accesses
 */
void dft_codelet_hc2r_2(R * R0, R * R1, const R * Cr, const R * Ci)
{
  {
    
    {
      E T1, T2;
      T1 = Cr[0];
      T2 = Cr[WSCR(1)];
      R1[0] = SUB(T1, T2);
      R0[0] = ADD(T1, T2);
    }
  }
}
