/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 16 -standalone -fma -generic-arith -compact -name dft_codelet_r2hc_16 */

/*
 * This function contains 58 FP additions, 20 FP multiplications,
 * (or, 38 additions, 0 multiplications, 20 fused multiply/add),
 * 34 stack variables, 3 constants, and 32 memory accesses
 */
void dft_codelet_r2hc_16(const R * R0, const R * R1, R * Cr, R * Ci)
{
  DK(KP923879532, +0.923879532511286756128183189396788286822416626);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  {
    
    {
      E T3, T6, T7, TN, TB, Ta, Td, Te, TO, TE, Tm, TT, Ty, TI, Tt;
      E TS, Tz, TL, TC, TD, TR, TU;
      {
        E T1, T2, T4, T5;
        T1 = R0[0];
        T2 = R0[WSR(4)];
        T3 = ADD(T1, T2);
        T4 = R0[WSR(2)];
        T5 = R0[WSR(6)];
        T6 = ADD(T4, T5);
        T7 = ADD(T3, T6);
        TN = SUB(T4, T5);
        TB = SUB(T1, T2);
      }
      {
        E T8, T9, Tb, Tc;
        T8 = R0[WSR(1)];
        T9 = R0[WSR(5)];
        Ta = ADD(T8, T9);
        TC = SUB(T8, T9);
        Tb = R0[WSR(7)];
        Tc = R0[WSR(3)];
        Td = ADD(Tb, Tc);
        TD = SUB(Tb, Tc);
      }
      Te = ADD(Ta, Td);
      TO = SUB(TD, TC);
      TE = ADD(TC, TD);
      {
        E Ti, TG, Tl, TH;
        {
          E Tg, Th, Tj, Tk;
          Tg = R1[0];
          Th = R1[WSR(4)];
          Ti = ADD(Tg, Th);
          TG = SUB(Tg, Th);
          Tj = R1[WSR(2)];
          Tk = R1[WSR(6)];
          Tl = ADD(Tj, Tk);
          TH = SUB(Tj, Tk);
        }
        Tm = SUB(Ti, Tl);
        TT = FMA(KP414213562, TG, TH);
        Ty = ADD(Ti, Tl);
        TI = FNMS(KP414213562, TH, TG);
      }
      {
        E Tp, TJ, Ts, TK;
        {
          E Tn, To, Tq, Tr;
          Tn = R1[WSR(7)];
          To = R1[WSR(3)];
          Tp = ADD(Tn, To);
          TJ = SUB(Tn, To);
          Tq = R1[WSR(1)];
          Tr = R1[WSR(5)];
          Ts = ADD(Tq, Tr);
          TK = SUB(Tr, Tq);
        }
        Tt = SUB(Tp, Ts);
        TS = FMA(KP414213562, TJ, TK);
        Tz = ADD(Tp, Ts);
        TL = FNMS(KP414213562, TK, TJ);
      }
      Cr[WSCR(4)] = SUB(T7, Te);
      Ci[WSCI(4)] = SUB(Tz, Ty);
      {
        E Tf, Tu, Tv, Tw;
        Tf = SUB(T3, T6);
        Tu = ADD(Tm, Tt);
        Cr[WSCR(6)] = FNMS(KP707106781, Tu, Tf);
        Cr[WSCR(2)] = FMA(KP707106781, Tu, Tf);
        Tv = SUB(Td, Ta);
        Tw = SUB(Tt, Tm);
        Ci[WSCI(2)] = FMA(KP707106781, Tw, Tv);
        Ci[WSCI(6)] = NEG(FNMS(KP707106781, Tw, Tv));
      }
      {
        E Tx, TA, TF, TM;
        Tx = ADD(T7, Te);
        TA = ADD(Ty, Tz);
        Cr[WSCR(8)] = SUB(Tx, TA);
        Cr[0] = ADD(Tx, TA);
        TF = FMA(KP707106781, TE, TB);
        TM = ADD(TI, TL);
        Cr[WSCR(7)] = FNMS(KP923879532, TM, TF);
        Cr[WSCR(1)] = FMA(KP923879532, TM, TF);
      }
      TR = FNMS(KP707106781, TO, TN);
      TU = SUB(TS, TT);
      Ci[WSCI(1)] = NEG(FNMS(KP923879532, TU, TR));
      Ci[WSCI(7)] = FMA(KP923879532, TU, TR);
      {
        E TV, TW, TP, TQ;
        TV = FNMS(KP707106781, TE, TB);
        TW = ADD(TT, TS);
        Cr[WSCR(5)] = FNMS(KP923879532, TW, TV);
        Cr[WSCR(3)] = FMA(KP923879532, TW, TV);
        TP = FMA(KP707106781, TO, TN);
        TQ = SUB(TL, TI);
        Ci[WSCI(3)] = FMA(KP923879532, TQ, TP);
        Ci[WSCI(5)] = NEG(FNMS(KP923879532, TQ, TP));
      }
    }
  }
}
