/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 15 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_15 */

/*
 * This function contains 64 FP additions, 43 FP multiplications,
 * (or, 21 additions, 0 multiplications, 43 fused multiply/add),
 * 46 stack variables, 9 constants, and 30 memory accesses
 */
void dft_codelet_hc2r_15(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP1_902113032, +1.902113032590307144232878666758764286811397268);
  DK(KP1_118033988, +1.118033988749894848204586834365638117720309180);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T3, Tt, Th, TC, TY, TZ, TD, TH, TI, Tm, Tu, Tr, Tv, T8, Td;
      E Te;
      {
        E Tg, T1, T2, Tf;
        Tg = Ci[WSCI(5)];
        T1 = Cr[0];
        T2 = Cr[WSCR(5)];
        Tf = SUB(T1, T2);
        T3 = FMA(KP2_000000000, T2, T1);
        Tt = FNMS(KP1_732050807, Tg, Tf);
        Th = FMA(KP1_732050807, Tg, Tf);
      }
      {
        E T4, TA, T9, TF, T5, T6, T7, Ta, Tb, Tc, Tq, TG, Tl, TB, Ti;
        E Tn;
        T4 = Cr[WSCR(3)];
        TA = Ci[WSCI(3)];
        T9 = Cr[WSCR(6)];
        TF = Ci[WSCI(6)];
        T5 = Cr[WSCR(7)];
        T6 = Cr[WSCR(2)];
        T7 = ADD(T5, T6);
        Ta = Cr[WSCR(4)];
        Tb = Cr[WSCR(1)];
        Tc = ADD(Ta, Tb);
        {
          E To, Tp, Tj, Tk;
          To = Ci[WSCI(4)];
          Tp = Ci[WSCI(1)];
          Tq = ADD(To, Tp);
          TG = SUB(Tp, To);
          Tj = Ci[WSCI(7)];
          Tk = Ci[WSCI(2)];
          Tl = SUB(Tj, Tk);
          TB = ADD(Tj, Tk);
        }
        TC = FMA(KP500000000, TB, TA);
        TY = ADD(TG, TF);
        TZ = SUB(TA, TB);
        TD = SUB(T5, T6);
        TH = FNMS(KP500000000, TG, TF);
        TI = SUB(Ta, Tb);
        Ti = FNMS(KP2_000000000, T4, T7);
        Tm = FMA(KP1_732050807, Tl, Ti);
        Tu = FNMS(KP1_732050807, Tl, Ti);
        Tn = FNMS(KP2_000000000, T9, Tc);
        Tr = FMA(KP1_732050807, Tq, Tn);
        Tv = FNMS(KP1_732050807, Tq, Tn);
        T8 = ADD(T4, T7);
        Td = ADD(T9, Tc);
        Te = ADD(T8, Td);
      }
      R0[0] = FMA(KP2_000000000, Te, T3);
      {
        E T10, T12, TX, T11, TV, TW;
        T10 = FNMS(KP618033988, TZ, TY);
        T12 = FMA(KP618033988, TY, TZ);
        TV = FNMS(KP500000000, Te, T3);
        TW = SUB(T8, Td);
        TX = FNMS(KP1_118033988, TW, TV);
        T11 = FMA(KP1_118033988, TW, TV);
        R1[WSR(1)] = FNMS(KP1_902113032, T10, TX);
        R1[WSR(4)] = FMA(KP1_902113032, T12, T11);
        R0[WSR(6)] = FMA(KP1_902113032, T10, TX);
        R0[WSR(3)] = FNMS(KP1_902113032, T12, T11);
      }
      {
        E TO, Ts, TN, TS, TU, TQ, TR, TT, TP;
        TO = SUB(Tr, Tm);
        Ts = ADD(Tm, Tr);
        TN = FMA(KP250000000, Ts, Th);
        TQ = FNMS(KP866025403, TI, TH);
        TR = FNMS(KP866025403, TD, TC);
        TS = FNMS(KP618033988, TR, TQ);
        TU = FMA(KP618033988, TQ, TR);
        R1[WSR(2)] = SUB(Th, Ts);
        TT = FMA(KP559016994, TO, TN);
        R1[WSR(5)] = FNMS(KP1_902113032, TU, TT);
        R0[WSR(7)] = FMA(KP1_902113032, TU, TT);
        TP = FNMS(KP559016994, TO, TN);
        R0[WSR(4)] = FNMS(KP1_902113032, TS, TP);
        R0[WSR(1)] = FMA(KP1_902113032, TS, TP);
      }
      {
        E Ty, Tw, Tx, TK, TM, TE, TJ, TL, Tz;
        Ty = SUB(Tv, Tu);
        Tw = ADD(Tu, Tv);
        Tx = FMA(KP250000000, Tw, Tt);
        TE = FMA(KP866025403, TD, TC);
        TJ = FMA(KP866025403, TI, TH);
        TK = FMA(KP618033988, TJ, TE);
        TM = FNMS(KP618033988, TE, TJ);
        R0[WSR(5)] = SUB(Tt, Tw);
        TL = FNMS(KP559016994, Ty, Tx);
        R1[WSR(6)] = FNMS(KP1_902113032, TM, TL);
        R1[WSR(3)] = FMA(KP1_902113032, TM, TL);
        Tz = FMA(KP559016994, Ty, Tx);
        R1[0] = FNMS(KP1_902113032, TK, Tz);
        R0[WSR(2)] = FMA(KP1_902113032, TK, Tz);
      }
    }
  }
}
