/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 20 -standalone -fma -generic-arith -compact -name dft_codelet_r2hc_20 */

/*
 * This function contains 86 FP additions, 32 FP multiplications,
 * (or, 58 additions, 4 multiplications, 28 fused multiply/add),
 * 51 stack variables, 4 constants, and 40 memory accesses
 */
void dft_codelet_r2hc_20(const R * R0, const R * R1, R * Cr, R * Ci)
{
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  {
    
    {
      E T3, T1d, TJ, TV, T16, T1k, T1l, T19, Ta, Th, Ti, T1e, T1f, T1g,
       TP;
      E TQ, TX, Tn, Ts, TK, TS, TT, TW, Ty, TD, TL;
      {
        E T1, T2, TF, TG, TH, TI;
        T1 = R0[0];
        T2 = R0[WSR(5)];
        TF = ADD(T1, T2);
        TG = R1[WSR(2)];
        TH = R1[WSR(7)];
        TI = ADD(TG, TH);
        T3 = SUB(T1, T2);
        T1d = SUB(TG, TH);
        TJ = SUB(TF, TI);
        TV = ADD(TF, TI);
      }
      {
        E T6, To, Tx, T17, TC, T18, T9, Tj, Td, Tu, Tm, T15, Tr, T14,
         Tg;
        E Tz;
        {
          E T4, T5, Tv, Tw;
          T4 = R0[WSR(2)];
          T5 = R0[WSR(7)];
          T6 = SUB(T4, T5);
          To = ADD(T4, T5);
          Tv = R1[WSR(6)];
          Tw = R1[WSR(1)];
          Tx = ADD(Tv, Tw);
          T17 = SUB(Tw, Tv);
        }
        {
          E TA, TB, T7, T8;
          TA = R1[WSR(8)];
          TB = R1[WSR(3)];
          TC = ADD(TA, TB);
          T18 = SUB(TB, TA);
          T7 = R0[WSR(8)];
          T8 = R0[WSR(3)];
          T9 = SUB(T7, T8);
          Tj = ADD(T7, T8);
        }
        {
          E Tb, Tc, Tk, Tl;
          Tb = R0[WSR(4)];
          Tc = R0[WSR(9)];
          Td = SUB(Tb, Tc);
          Tu = ADD(Tb, Tc);
          Tk = R1[0];
          Tl = R1[WSR(5)];
          Tm = ADD(Tk, Tl);
          T15 = SUB(Tl, Tk);
        }
        {
          E Tp, Tq, Te, Tf;
          Tp = R1[WSR(4)];
          Tq = R1[WSR(9)];
          Tr = ADD(Tp, Tq);
          T14 = SUB(Tq, Tp);
          Te = R0[WSR(6)];
          Tf = R0[WSR(1)];
          Tg = SUB(Te, Tf);
          Tz = ADD(Te, Tf);
        }
        T16 = SUB(T14, T15);
        T1k = SUB(T6, T9);
        T1l = SUB(Td, Tg);
        T19 = SUB(T17, T18);
        Ta = ADD(T6, T9);
        Th = ADD(Td, Tg);
        Ti = ADD(Ta, Th);
        T1e = ADD(T14, T15);
        T1f = ADD(T17, T18);
        T1g = ADD(T1e, T1f);
        TP = ADD(Tu, Tx);
        TQ = ADD(Tz, TC);
        TX = ADD(TP, TQ);
        Tn = SUB(Tj, Tm);
        Ts = SUB(To, Tr);
        TK = ADD(Ts, Tn);
        TS = ADD(To, Tr);
        TT = ADD(Tj, Tm);
        TW = ADD(TS, TT);
        Ty = SUB(Tu, Tx);
        TD = SUB(Tz, TC);
        TL = ADD(Ty, TD);
      }
      Cr[WSCR(5)] = ADD(T3, Ti);
      Ci[WSCI(5)] = SUB(T1g, T1d);
      {
        E Tt, TE, TR, TU;
        Tt = SUB(Tn, Ts);
        TE = SUB(Ty, TD);
        Ci[WSCI(6)] = MUL(KP951056516, FNMS(KP618033988, TE, Tt));
        Ci[WSCI(2)] = MUL(KP951056516, FMA(KP618033988, Tt, TE));
        TR = SUB(TP, TQ);
        TU = SUB(TS, TT);
        Ci[WSCI(8)] = NEG(MUL(KP951056516, FNMS(KP618033988, TU, TR)));
        Ci[WSCI(4)] = MUL(KP951056516, FMA(KP618033988, TR, TU));
      }
      {
        E T10, TY, TZ, TO, TM, TN;
        T10 = SUB(TW, TX);
        TY = ADD(TW, TX);
        TZ = FNMS(KP250000000, TY, TV);
        Cr[WSCR(4)] = FMA(KP559016994, T10, TZ);
        Cr[0] = ADD(TV, TY);
        Cr[WSCR(8)] = FNMS(KP559016994, T10, TZ);
        TO = SUB(TK, TL);
        TM = ADD(TK, TL);
        TN = FNMS(KP250000000, TM, TJ);
        Cr[WSCR(2)] = FNMS(KP559016994, TO, TN);
        Cr[WSCR(10)] = ADD(TJ, TM);
        Cr[WSCR(6)] = FMA(KP559016994, TO, TN);
      }
      {
        E T1a, T1c, T13, T1b, T11, T12;
        T1a = FMA(KP618033988, T19, T16);
        T1c = FNMS(KP618033988, T16, T19);
        T11 = FNMS(KP250000000, Ti, T3);
        T12 = SUB(Ta, Th);
        T13 = FMA(KP559016994, T12, T11);
        T1b = FNMS(KP559016994, T12, T11);
        Cr[WSCR(9)] = FNMS(KP951056516, T1a, T13);
        Cr[WSCR(7)] = FMA(KP951056516, T1c, T1b);
        Cr[WSCR(1)] = FMA(KP951056516, T1a, T13);
        Cr[WSCR(3)] = FNMS(KP951056516, T1c, T1b);
      }
      {
        E T1m, T1o, T1j, T1n, T1h, T1i;
        T1m = FMA(KP618033988, T1l, T1k);
        T1o = FNMS(KP618033988, T1k, T1l);
        T1h = FMA(KP250000000, T1g, T1d);
        T1i = SUB(T1e, T1f);
        T1j = FNMS(KP559016994, T1i, T1h);
        T1n = FMA(KP559016994, T1i, T1h);
        Ci[WSCI(1)] = NEG(FMA(KP951056516, T1m, T1j));
        Ci[WSCI(7)] = FMA(KP951056516, T1o, T1n);
        Ci[WSCI(9)] = NEG(FNMS(KP951056516, T1m, T1j));
        Ci[WSCI(3)] = FNMS(KP951056516, T1o, T1n);
      }
    }
  }
}
