/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 4 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_4 */

/*
 * This function contains 6 FP additions, 4 FP multiplications,
 * (or, 2 additions, 0 multiplications, 4 fused multiply/add),
 * 8 stack variables, 1 constants, and 8 memory accesses
 */
void dft_codelet_hc2r_4(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T4, T6, T3, T5, T1, T2;
      T4 = Cr[WSCR(1)];
      T6 = Ci[WSCI(1)];
      T1 = Cr[0];
      T2 = Cr[WSCR(2)];
      T3 = ADD(T1, T2);
      T5 = SUB(T1, T2);
      R0[WSR(1)] = FNMS(KP2_000000000, T4, T3);
      R1[WSR(1)] = FMA(KP2_000000000, T6, T5);
      R0[0] = FMA(KP2_000000000, T4, T3);
      R1[0] = FNMS(KP2_000000000, T6, T5);
    }
  }
}
