/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 16 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_16 */

/*
 * This function contains 58 FP additions, 32 FP multiplications,
 * (or, 26 additions, 0 multiplications, 32 fused multiply/add),
 * 31 stack variables, 4 constants, and 32 memory accesses
 */
void dft_codelet_hc2r_16(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP1_847759065, +1.847759065022573512256366378793576573644833252);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  DK(KP1_414213562, +1.414213562373095048801688724209698078569671875);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T5, TL, Tj, TD, T8, TM, To, TE, Tc, TP, Tf, TQ, Tu, Tz, TR;
      E TO, TH, TG;
      {
        E T4, Ti, T3, Th, T1, T2;
        T4 = Cr[WSCR(4)];
        Ti = Ci[WSCI(4)];
        T1 = Cr[0];
        T2 = Cr[WSCR(8)];
        T3 = ADD(T1, T2);
        Th = SUB(T1, T2);
        T5 = FMA(KP2_000000000, T4, T3);
        TL = FNMS(KP2_000000000, T4, T3);
        Tj = FNMS(KP2_000000000, Ti, Th);
        TD = FMA(KP2_000000000, Ti, Th);
      }
      {
        E T6, T7, Tk, Tl, Tm, Tn;
        T6 = Cr[WSCR(2)];
        T7 = Cr[WSCR(6)];
        Tk = SUB(T6, T7);
        Tl = Ci[WSCI(2)];
        Tm = Ci[WSCI(6)];
        Tn = ADD(Tl, Tm);
        T8 = ADD(T6, T7);
        TM = SUB(Tl, Tm);
        To = SUB(Tk, Tn);
        TE = ADD(Tk, Tn);
      }
      {
        E Tq, Ty, Tv, Tt;
        {
          E Ta, Tb, Tw, Tx;
          Ta = Cr[WSCR(1)];
          Tb = Cr[WSCR(7)];
          Tc = ADD(Ta, Tb);
          Tq = SUB(Ta, Tb);
          Tw = Ci[WSCI(1)];
          Tx = Ci[WSCI(7)];
          Ty = ADD(Tw, Tx);
          TP = SUB(Tw, Tx);
        }
        {
          E Td, Te, Tr, Ts;
          Td = Cr[WSCR(5)];
          Te = Cr[WSCR(3)];
          Tf = ADD(Td, Te);
          Tv = SUB(Td, Te);
          Tr = Ci[WSCI(5)];
          Ts = Ci[WSCI(3)];
          Tt = ADD(Tr, Ts);
          TQ = SUB(Tr, Ts);
        }
        Tu = SUB(Tq, Tt);
        Tz = ADD(Tv, Ty);
        TR = SUB(TP, TQ);
        TO = SUB(Tc, Tf);
        TH = ADD(Tq, Tt);
        TG = SUB(Ty, Tv);
      }
      {
        E T9, Tg, TT, TU;
        T9 = FMA(KP2_000000000, T8, T5);
        Tg = ADD(Tc, Tf);
        R0[WSR(4)] = FNMS(KP2_000000000, Tg, T9);
        R0[0] = FMA(KP2_000000000, Tg, T9);
        TT = FMA(KP2_000000000, TM, TL);
        TU = ADD(TO, TR);
        R0[WSR(3)] = FNMS(KP1_414213562, TU, TT);
        R0[WSR(7)] = FMA(KP1_414213562, TU, TT);
      }
      {
        E TV, TW, Tp, TA;
        TV = FNMS(KP2_000000000, T8, T5);
        TW = ADD(TQ, TP);
        R0[WSR(2)] = FNMS(KP2_000000000, TW, TV);
        R0[WSR(6)] = FMA(KP2_000000000, TW, TV);
        Tp = FMA(KP1_414213562, To, Tj);
        TA = FNMS(KP414213562, Tz, Tu);
        R1[WSR(4)] = FNMS(KP1_847759065, TA, Tp);
        R1[0] = FMA(KP1_847759065, TA, Tp);
      }
      {
        E TB, TC, TJ, TK;
        TB = FNMS(KP1_414213562, To, Tj);
        TC = FMA(KP414213562, Tu, Tz);
        R1[WSR(2)] = FNMS(KP1_847759065, TC, TB);
        R1[WSR(6)] = FMA(KP1_847759065, TC, TB);
        TJ = FMA(KP1_414213562, TE, TD);
        TK = FMA(KP414213562, TG, TH);
        R1[WSR(3)] = FNMS(KP1_847759065, TK, TJ);
        R1[WSR(7)] = FMA(KP1_847759065, TK, TJ);
      }
      {
        E TN, TS, TF, TI;
        TN = FNMS(KP2_000000000, TM, TL);
        TS = SUB(TO, TR);
        R0[WSR(5)] = FNMS(KP1_414213562, TS, TN);
        R0[WSR(1)] = FMA(KP1_414213562, TS, TN);
        TF = FNMS(KP1_414213562, TE, TD);
        TI = FNMS(KP414213562, TH, TG);
        R1[WSR(1)] = FNMS(KP1_847759065, TI, TF);
        R1[WSR(5)] = FMA(KP1_847759065, TI, TF);
      }
    }
  }
}
