/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 8 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_8 */

/*
 * This function contains 20 FP additions, 12 FP multiplications,
 * (or, 8 additions, 0 multiplications, 12 fused multiply/add),
 * 19 stack variables, 2 constants, and 16 memory accesses
 */
void dft_codelet_hc2r_8(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP1_414213562, +1.414213562373095048801688724209698078569671875);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T4, Ta, T3, T9, T8, Tc, Tf, Tk, T1, T2, T5, Tj;
      T4 = Cr[WSCR(2)];
      Ta = Ci[WSCI(2)];
      T1 = Cr[0];
      T2 = Cr[WSCR(4)];
      T3 = ADD(T1, T2);
      T9 = SUB(T1, T2);
      {
        E T6, T7, Td, Te;
        T6 = Cr[WSCR(1)];
        T7 = Cr[WSCR(3)];
        T8 = ADD(T6, T7);
        Tc = SUB(T6, T7);
        Td = Ci[WSCI(1)];
        Te = Ci[WSCI(3)];
        Tf = ADD(Td, Te);
        Tk = SUB(Td, Te);
      }
      T5 = FMA(KP2_000000000, T4, T3);
      R0[WSR(2)] = FNMS(KP2_000000000, T8, T5);
      R0[0] = FMA(KP2_000000000, T8, T5);
      Tj = FNMS(KP2_000000000, T4, T3);
      R0[WSR(1)] = FNMS(KP2_000000000, Tk, Tj);
      R0[WSR(3)] = FMA(KP2_000000000, Tk, Tj);
      {
        E Tb, Tg, Th, Ti;
        Tb = FNMS(KP2_000000000, Ta, T9);
        Tg = SUB(Tc, Tf);
        R1[WSR(2)] = FNMS(KP1_414213562, Tg, Tb);
        R1[0] = FMA(KP1_414213562, Tg, Tb);
        Th = FMA(KP2_000000000, Ta, T9);
        Ti = ADD(Tc, Tf);
        R1[WSR(1)] = FNMS(KP1_414213562, Ti, Th);
        R1[WSR(3)] = FMA(KP1_414213562, Ti, Th);
      }
    }
  }
}
