/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 120 -standalone -fma -generic-arith -compact -name dft_codelet_r2cf_120 */

/*
 * This function contains 896 FP additions, 382 FP multiplications,
 * (or, 528 additions, 14 multiplications, 368 fused multiply/add),
 * 174 stack variables, 9 constants, and 240 memory accesses
 */
void dft_codelet_r2cf_120(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP910592997, +0.910592997310029334643087372129977886038870291);
  DK(KP823639103, +0.823639103546331925877420039278190003029660514);
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ivs, R1 = R1 + ivs, Cr = Cr + ovs, Ci = Ci + ovs, MAKE_VOLATILE_STRIDE(480, rs), MAKE_VOLATILE_STRIDE(480, csr), MAKE_VOLATILE_STRIDE(480, csi)) {
      E T9u, TaW, T23, T4j, T5H, T7j, Tds, Tdt, Tdu, T7, Tm, T9n, TaT,
       TaU, TaV;
      E Tcs, Tcv, Td2, T2m, T7o, T4S, T5I, T4m, T5K, Td1, Tdr, T7m,
       T8M, T1S, Tae;
      E Ta6, Tax, TbE, Tbg, TcP, TcQ, Tcn, TcR, TdM, TdP, TdQ, Te8,
       T4g, T8B, T7R;
      E T5t, T72, T6c, T7Q, T8C, T8a, T4I, T6d, T5m, TK, Taa, T9E, TaF,
       TbA, Tbd;
      E Tcz, TcA, Tc1, TcB, Tdw, Tdz, TdA, Tec, T2Q, T8x, T7v, T51,
       T6Z, T5Q, T7u;
      E T8y, T86, T4s, T5R, T4U, T17, Tab, T9N, TaM, TbB, Tbc, TcE,
       TcF, Tc8, TcG;
      E TdB, TdE, TdF, Teb, T3j, T8u, T7C, T5a, T6Y, T5X, T7B, T8v,
       T87, T4x, T5Y;
      E T53, T1v, Tad, T9X, Taq, TbD, Tbf, TcK, TcL, Tcg, TcM, TdH,
       TdK, TdL, Te9;
      E T3N, T8E, T7K, T5k, T71, T65, T7J, T8F, T89, T4D, T66, T5d;
      {
        E T3, T5F, T1Y, TaR, T21, TaS, T6, T1V, Te, Tct, T24, T4P, Tl,
         Tcq, T2d;
        E T4M, T2b, Tcu, T4Q, T9q, T2k, Tcr, T4N, T9t;
        {
          E T1, T2, T1W, T1X;
          T1 = R0[0];
          T2 = R0[WS(rs, 30)];
          T3 = ADD(T1, T2);
          T5F = SUB(T1, T2);
          T1W = R1[WS(rs, 52)];
          T1X = R1[WS(rs, 22)];
          T1Y = SUB(T1W, T1X);
          TaR = ADD(T1W, T1X);
        }
        {
          E T1Z, T20, T4, T5;
          T1Z = R1[WS(rs, 7)];
          T20 = R1[WS(rs, 37)];
          T21 = SUB(T1Z, T20);
          TaS = ADD(T1Z, T20);
          T4 = R0[WS(rs, 15)];
          T5 = R0[WS(rs, 45)];
          T6 = ADD(T4, T5);
          T1V = SUB(T4, T5);
        }
        {
          E T8, T9, Ta, Tb, Tc, Td;
          T8 = R0[WS(rs, 20)];
          T9 = R0[WS(rs, 50)];
          Ta = ADD(T8, T9);
          Tb = R0[WS(rs, 35)];
          Tc = R0[WS(rs, 5)];
          Td = ADD(Tb, Tc);
          Te = SUB(Ta, Td);
          Tct = ADD(Ta, Td);
          T24 = SUB(Tb, Tc);
          T4P = SUB(T8, T9);
        }
        {
          E Tf, Tg, Th, Ti, Tj, Tk;
          Tf = R0[WS(rs, 40)];
          Tg = R0[WS(rs, 10)];
          Th = ADD(Tf, Tg);
          Ti = R0[WS(rs, 55)];
          Tj = R0[WS(rs, 25)];
          Tk = ADD(Ti, Tj);
          Tl = SUB(Th, Tk);
          Tcq = ADD(Th, Tk);
          T2d = SUB(Ti, Tj);
          T4M = SUB(Tf, Tg);
        }
        {
          E T27, T9o, T2a, T9p;
          {
            E T25, T26, T28, T29;
            T25 = R1[WS(rs, 12)];
            T26 = R1[WS(rs, 42)];
            T27 = SUB(T25, T26);
            T9o = ADD(T25, T26);
            T28 = R1[WS(rs, 27)];
            T29 = R1[WS(rs, 57)];
            T2a = SUB(T28, T29);
            T9p = ADD(T28, T29);
          }
          T2b = SUB(T27, T2a);
          Tcu = ADD(T9p, T9o);
          T4Q = ADD(T2a, T27);
          T9q = SUB(T9o, T9p);
        }
        {
          E T2g, T9r, T2j, T9s;
          {
            E T2e, T2f, T2h, T2i;
            T2e = R1[WS(rs, 32)];
            T2f = R1[WS(rs, 2)];
            T2g = SUB(T2e, T2f);
            T9r = ADD(T2e, T2f);
            T2h = R1[WS(rs, 47)];
            T2i = R1[WS(rs, 17)];
            T2j = SUB(T2h, T2i);
            T9s = ADD(T2h, T2i);
          }
          T2k = SUB(T2g, T2j);
          Tcr = ADD(T9s, T9r);
          T4N = ADD(T2j, T2g);
          T9t = SUB(T9r, T9s);
        }
        {
          E T22, T5G, T2c, T2l;
          T9u = SUB(T9q, T9t);
          TaW = SUB(Tl, Te);
          T22 = SUB(T1Y, T21);
          T23 = FNMS(KP707106781, T22, T1V);
          T4j = FMA(KP707106781, T22, T1V);
          T5G = ADD(T21, T1Y);
          T5H = FNMS(KP707106781, T5G, T5F);
          T7j = FMA(KP707106781, T5G, T5F);
          Tds = ADD(Tct, Tcu);
          Tdt = ADD(Tcq, Tcr);
          Tdu = ADD(Tds, Tdt);
          T7 = SUB(T3, T6);
          Tm = ADD(Te, Tl);
          T9n = FNMS(KP500000000, Tm, T7);
          TaT = SUB(TaR, TaS);
          TaU = ADD(T9q, T9t);
          TaV = FNMS(KP500000000, TaU, TaT);
          Tcs = SUB(Tcq, Tcr);
          Tcv = SUB(Tct, Tcu);
          Td2 = ADD(Tcv, Tcs);
          T2c = FNMS(KP707106781, T2b, T24);
          T2l = FNMS(KP707106781, T2k, T2d);
          T2m = ADD(T2c, T2l);
          T7o = SUB(T2l, T2c);
          {
            E T4O, T4R, T4k, T4l;
            T4O = FNMS(KP707106781, T4N, T4M);
            T4R = FNMS(KP707106781, T4Q, T4P);
            T4S = SUB(T4O, T4R);
            T5I = ADD(T4R, T4O);
            T4k = FMA(KP707106781, T2b, T24);
            T4l = FMA(KP707106781, T2k, T2d);
            T4m = ADD(T4k, T4l);
            T5K = SUB(T4l, T4k);
          }
          {
            E TcZ, Td0, T7k, T7l;
            TcZ = ADD(T3, T6);
            Td0 = ADD(TaS, TaR);
            Td1 = SUB(TcZ, Td0);
            Tdr = ADD(TcZ, Td0);
            T7k = FMA(KP707106781, T4Q, T4P);
            T7l = FMA(KP707106781, T4N, T4M);
            T7m = ADD(T7k, T7l);
            T8M = SUB(T7l, T7k);
          }
        }
      }
      {
        E T1C, TcN, T3O, T68, T1J, Tch, T3X, T5n, T1Q, Tck, T46, T5q,
         T4d, Tcl, T5r;
        E Ta1, T44, Tci, T5o, Ta4, T3V, TcO, T69, Tat;
        {
          E T1w, T1x, T1y, T1z, T1A, T1B;
          T1w = R0[WS(rs, 36)];
          T1x = R0[WS(rs, 6)];
          T1y = ADD(T1w, T1x);
          T1z = R0[WS(rs, 51)];
          T1A = R0[WS(rs, 21)];
          T1B = ADD(T1z, T1A);
          T1C = SUB(T1y, T1B);
          TcN = ADD(T1y, T1B);
          T3O = SUB(T1z, T1A);
          T68 = SUB(T1w, T1x);
        }
        {
          E T1D, T1E, T1F, T1G, T1H, T1I;
          T1D = R0[WS(rs, 56)];
          T1E = R0[WS(rs, 26)];
          T1F = ADD(T1D, T1E);
          T1G = R0[WS(rs, 11)];
          T1H = R0[WS(rs, 41)];
          T1I = ADD(T1G, T1H);
          T1J = SUB(T1F, T1I);
          Tch = ADD(T1F, T1I);
          T3X = SUB(T1G, T1H);
          T5n = SUB(T1D, T1E);
        }
        {
          E T1K, T1L, T1M, T1N, T1O, T1P;
          T1K = R0[WS(rs, 16)];
          T1L = R0[WS(rs, 46)];
          T1M = ADD(T1K, T1L);
          T1N = R0[WS(rs, 31)];
          T1O = R0[WS(rs, 1)];
          T1P = ADD(T1N, T1O);
          T1Q = SUB(T1M, T1P);
          Tck = ADD(T1M, T1P);
          T46 = SUB(T1N, T1O);
          T5q = SUB(T1K, T1L);
        }
        {
          E T49, T9Z, T4c, Ta0;
          {
            E T47, T48, T4a, T4b;
            T47 = R1[WS(rs, 23)];
            T48 = R1[WS(rs, 53)];
            T49 = SUB(T47, T48);
            T9Z = ADD(T47, T48);
            T4a = R1[WS(rs, 8)];
            T4b = R1[WS(rs, 38)];
            T4c = SUB(T4a, T4b);
            Ta0 = ADD(T4a, T4b);
          }
          T4d = SUB(T49, T4c);
          Tcl = ADD(T9Z, Ta0);
          T5r = ADD(T49, T4c);
          Ta1 = SUB(T9Z, Ta0);
        }
        {
          E T40, Ta2, T43, Ta3;
          {
            E T3Y, T3Z, T41, T42;
            T3Y = R1[WS(rs, 3)];
            T3Z = R1[WS(rs, 33)];
            T40 = SUB(T3Y, T3Z);
            Ta2 = ADD(T3Y, T3Z);
            T41 = R1[WS(rs, 48)];
            T42 = R1[WS(rs, 18)];
            T43 = SUB(T41, T42);
            Ta3 = ADD(T41, T42);
          }
          T44 = SUB(T40, T43);
          Tci = ADD(Ta2, Ta3);
          T5o = ADD(T40, T43);
          Ta4 = SUB(Ta2, Ta3);
        }
        {
          E T3R, Tar, T3U, Tas;
          {
            E T3P, T3Q, T3S, T3T;
            T3P = R1[WS(rs, 28)];
            T3Q = R1[WS(rs, 58)];
            T3R = SUB(T3P, T3Q);
            Tar = ADD(T3P, T3Q);
            T3S = R1[WS(rs, 43)];
            T3T = R1[WS(rs, 13)];
            T3U = SUB(T3S, T3T);
            Tas = ADD(T3S, T3T);
          }
          T3V = SUB(T3R, T3U);
          TcO = ADD(Tas, Tar);
          T69 = ADD(T3U, T3R);
          Tat = SUB(Tar, Tas);
        }
        {
          E Ta5, T1R, T9Y, Taw, Tau, Tav;
          Ta5 = SUB(Ta1, Ta4);
          T1R = ADD(T1J, T1Q);
          T9Y = FNMS(KP500000000, T1R, T1C);
          T1S = ADD(T1C, T1R);
          Tae = FMA(KP866025403, Ta5, T9Y);
          Ta6 = FNMS(KP866025403, Ta5, T9Y);
          Taw = SUB(T1Q, T1J);
          Tau = ADD(Ta4, Ta1);
          Tav = FMA(KP500000000, Tau, Tat);
          Tax = FNMS(KP866025403, Taw, Tav);
          TbE = SUB(Tau, Tat);
          Tbg = FMA(KP866025403, Taw, Tav);
        }
        {
          E Tcj, Tcm, TdN, TdO;
          TcP = SUB(TcN, TcO);
          Tcj = SUB(Tch, Tci);
          Tcm = SUB(Tck, Tcl);
          TcQ = ADD(Tcj, Tcm);
          Tcn = SUB(Tcj, Tcm);
          TcR = FNMS(KP500000000, TcQ, TcP);
          TdM = ADD(TcN, TcO);
          TdN = ADD(Tch, Tci);
          TdO = ADD(Tck, Tcl);
          TdP = ADD(TdN, TdO);
          TdQ = FNMS(KP500000000, TdP, TdM);
          Te8 = SUB(TdO, TdN);
        }
        {
          E T3W, T45, T4e, T4f;
          T3W = FNMS(KP707106781, T3V, T3O);
          T45 = FMA(KP707106781, T44, T3X);
          T4e = FMA(KP707106781, T4d, T46);
          T4f = ADD(T45, T4e);
          T4g = ADD(T3W, T4f);
          T8B = FNMS(KP500000000, T4f, T3W);
          T7R = SUB(T4e, T45);
        }
        {
          E T6a, T5p, T5s, T6b;
          T6a = FNMS(KP707106781, T69, T68);
          T5p = FNMS(KP707106781, T5o, T5n);
          T5s = FNMS(KP707106781, T5r, T5q);
          T6b = ADD(T5p, T5s);
          T5t = SUB(T5p, T5s);
          T72 = ADD(T6a, T6b);
          T6c = FNMS(KP500000000, T6b, T6a);
        }
        {
          E T7M, T7N, T7O, T7P;
          T7M = FMA(KP707106781, T69, T68);
          T7N = FMA(KP707106781, T5o, T5n);
          T7O = FMA(KP707106781, T5r, T5q);
          T7P = ADD(T7N, T7O);
          T7Q = FNMS(KP500000000, T7P, T7M);
          T8C = SUB(T7O, T7N);
          T8a = ADD(T7M, T7P);
        }
        {
          E T4E, T4F, T4G, T4H;
          T4E = FMA(KP707106781, T3V, T3O);
          T4F = FNMS(KP707106781, T44, T3X);
          T4G = FNMS(KP707106781, T4d, T46);
          T4H = ADD(T4F, T4G);
          T4I = ADD(T4E, T4H);
          T6d = SUB(T4G, T4F);
          T5m = FNMS(KP500000000, T4H, T4E);
        }
      }
      {
        E Tu, Tcx, T2o, T5M, TB, TbV, T2x, T4V, TI, TbY, T2G, T4Y, T2N,
         TbZ, T4Z;
        E T9z, T2E, TbW, T4W, T9C, T2v, Tcy, T5N, TaB;
        {
          E To, Tp, Tq, Tr, Ts, Tt;
          To = R0[WS(rs, 12)];
          Tp = R0[WS(rs, 42)];
          Tq = ADD(To, Tp);
          Tr = R0[WS(rs, 27)];
          Ts = R0[WS(rs, 57)];
          Tt = ADD(Tr, Ts);
          Tu = SUB(Tq, Tt);
          Tcx = ADD(Tq, Tt);
          T2o = SUB(Tr, Ts);
          T5M = SUB(To, Tp);
        }
        {
          E Tv, Tw, Tx, Ty, Tz, TA;
          Tv = R0[WS(rs, 32)];
          Tw = R0[WS(rs, 2)];
          Tx = ADD(Tv, Tw);
          Ty = R0[WS(rs, 47)];
          Tz = R0[WS(rs, 17)];
          TA = ADD(Ty, Tz);
          TB = SUB(Tx, TA);
          TbV = ADD(Tx, TA);
          T2x = SUB(Ty, Tz);
          T4V = SUB(Tv, Tw);
        }
        {
          E TC, TD, TE, TF, TG, TH;
          TC = R0[WS(rs, 52)];
          TD = R0[WS(rs, 22)];
          TE = ADD(TC, TD);
          TF = R0[WS(rs, 7)];
          TG = R0[WS(rs, 37)];
          TH = ADD(TF, TG);
          TI = SUB(TE, TH);
          TbY = ADD(TE, TH);
          T2G = SUB(TF, TG);
          T4Y = SUB(TC, TD);
        }
        {
          E T2J, T9x, T2M, T9y;
          {
            E T2H, T2I, T2K, T2L;
            T2H = R1[WS(rs, 59)];
            T2I = R1[WS(rs, 29)];
            T2J = SUB(T2H, T2I);
            T9x = ADD(T2H, T2I);
            T2K = R1[WS(rs, 44)];
            T2L = R1[WS(rs, 14)];
            T2M = SUB(T2K, T2L);
            T9y = ADD(T2K, T2L);
          }
          T2N = SUB(T2J, T2M);
          TbZ = ADD(T9x, T9y);
          T4Z = ADD(T2J, T2M);
          T9z = SUB(T9x, T9y);
        }
        {
          E T2A, T9A, T2D, T9B;
          {
            E T2y, T2z, T2B, T2C;
            T2y = R1[WS(rs, 39)];
            T2z = R1[WS(rs, 9)];
            T2A = SUB(T2y, T2z);
            T9A = ADD(T2y, T2z);
            T2B = R1[WS(rs, 24)];
            T2C = R1[WS(rs, 54)];
            T2D = SUB(T2B, T2C);
            T9B = ADD(T2B, T2C);
          }
          T2E = SUB(T2A, T2D);
          TbW = ADD(T9A, T9B);
          T4W = ADD(T2A, T2D);
          T9C = SUB(T9A, T9B);
        }
        {
          E T2r, Taz, T2u, TaA;
          {
            E T2p, T2q, T2s, T2t;
            T2p = R1[WS(rs, 4)];
            T2q = R1[WS(rs, 34)];
            T2r = SUB(T2p, T2q);
            Taz = ADD(T2p, T2q);
            T2s = R1[WS(rs, 19)];
            T2t = R1[WS(rs, 49)];
            T2u = SUB(T2s, T2t);
            TaA = ADD(T2s, T2t);
          }
          T2v = SUB(T2r, T2u);
          Tcy = ADD(TaA, Taz);
          T5N = ADD(T2u, T2r);
          TaB = SUB(Taz, TaA);
        }
        {
          E T9D, TJ, T9w, TaE, TaC, TaD;
          T9D = SUB(T9z, T9C);
          TJ = ADD(TB, TI);
          T9w = FNMS(KP500000000, TJ, Tu);
          TK = ADD(Tu, TJ);
          Taa = FMA(KP866025403, T9D, T9w);
          T9E = FNMS(KP866025403, T9D, T9w);
          TaE = SUB(TI, TB);
          TaC = ADD(T9C, T9z);
          TaD = FMA(KP500000000, TaC, TaB);
          TaF = FNMS(KP866025403, TaE, TaD);
          TbA = SUB(TaC, TaB);
          Tbd = FMA(KP866025403, TaE, TaD);
        }
        {
          E TbX, Tc0, Tdx, Tdy;
          Tcz = SUB(Tcx, Tcy);
          TbX = SUB(TbV, TbW);
          Tc0 = SUB(TbY, TbZ);
          TcA = ADD(TbX, Tc0);
          Tc1 = SUB(TbX, Tc0);
          TcB = FNMS(KP500000000, TcA, Tcz);
          Tdw = ADD(Tcx, Tcy);
          Tdx = ADD(TbV, TbW);
          Tdy = ADD(TbY, TbZ);
          Tdz = ADD(Tdx, Tdy);
          TdA = FNMS(KP500000000, Tdz, Tdw);
          Tec = SUB(Tdy, Tdx);
        }
        {
          E T2w, T2F, T2O, T2P;
          T2w = FNMS(KP707106781, T2v, T2o);
          T2F = FMA(KP707106781, T2E, T2x);
          T2O = FMA(KP707106781, T2N, T2G);
          T2P = ADD(T2F, T2O);
          T2Q = ADD(T2w, T2P);
          T8x = FNMS(KP500000000, T2P, T2w);
          T7v = SUB(T2O, T2F);
        }
        {
          E T5O, T4X, T50, T5P;
          T5O = FNMS(KP707106781, T5N, T5M);
          T4X = FNMS(KP707106781, T4W, T4V);
          T50 = FNMS(KP707106781, T4Z, T4Y);
          T5P = ADD(T4X, T50);
          T51 = SUB(T4X, T50);
          T6Z = ADD(T5O, T5P);
          T5Q = FNMS(KP500000000, T5P, T5O);
        }
        {
          E T7q, T7r, T7s, T7t;
          T7q = FMA(KP707106781, T5N, T5M);
          T7r = FMA(KP707106781, T4W, T4V);
          T7s = FMA(KP707106781, T4Z, T4Y);
          T7t = ADD(T7r, T7s);
          T7u = FNMS(KP500000000, T7t, T7q);
          T8y = SUB(T7s, T7r);
          T86 = ADD(T7q, T7t);
        }
        {
          E T4o, T4p, T4q, T4r;
          T4o = FMA(KP707106781, T2v, T2o);
          T4p = FNMS(KP707106781, T2E, T2x);
          T4q = FNMS(KP707106781, T2N, T2G);
          T4r = ADD(T4p, T4q);
          T4s = ADD(T4o, T4r);
          T5R = SUB(T4q, T4p);
          T4U = FNMS(KP500000000, T4r, T4o);
        }
      }
      {
        E TR, TcC, T2R, T5T, TY, Tc2, T30, T54, T15, Tc5, T39, T57,
         T3g, Tc6, T58;
        E T9I, T37, Tc3, T55, T9L, T2Y, TcD, T5U, TaI;
        {
          E TL, TM, TN, TO, TP, TQ;
          TL = R0[WS(rs, 48)];
          TM = R0[WS(rs, 18)];
          TN = ADD(TL, TM);
          TO = R0[WS(rs, 3)];
          TP = R0[WS(rs, 33)];
          TQ = ADD(TO, TP);
          TR = SUB(TN, TQ);
          TcC = ADD(TN, TQ);
          T2R = SUB(TO, TP);
          T5T = SUB(TL, TM);
        }
        {
          E TS, TT, TU, TV, TW, TX;
          TS = R0[WS(rs, 8)];
          TT = R0[WS(rs, 38)];
          TU = ADD(TS, TT);
          TV = R0[WS(rs, 23)];
          TW = R0[WS(rs, 53)];
          TX = ADD(TV, TW);
          TY = SUB(TU, TX);
          Tc2 = ADD(TU, TX);
          T30 = SUB(TV, TW);
          T54 = SUB(TS, TT);
        }
        {
          E TZ, T10, T11, T12, T13, T14;
          TZ = R0[WS(rs, 28)];
          T10 = R0[WS(rs, 58)];
          T11 = ADD(TZ, T10);
          T12 = R0[WS(rs, 43)];
          T13 = R0[WS(rs, 13)];
          T14 = ADD(T12, T13);
          T15 = SUB(T11, T14);
          Tc5 = ADD(T11, T14);
          T39 = SUB(T12, T13);
          T57 = SUB(TZ, T10);
        }
        {
          E T3c, T9G, T3f, T9H;
          {
            E T3a, T3b, T3d, T3e;
            T3a = R1[WS(rs, 35)];
            T3b = R1[WS(rs, 5)];
            T3c = SUB(T3a, T3b);
            T9G = ADD(T3a, T3b);
            T3d = R1[WS(rs, 20)];
            T3e = R1[WS(rs, 50)];
            T3f = SUB(T3d, T3e);
            T9H = ADD(T3d, T3e);
          }
          T3g = SUB(T3c, T3f);
          Tc6 = ADD(T9G, T9H);
          T58 = ADD(T3c, T3f);
          T9I = SUB(T9G, T9H);
        }
        {
          E T33, T9J, T36, T9K;
          {
            E T31, T32, T34, T35;
            T31 = R1[WS(rs, 15)];
            T32 = R1[WS(rs, 45)];
            T33 = SUB(T31, T32);
            T9J = ADD(T31, T32);
            T34 = R1[0];
            T35 = R1[WS(rs, 30)];
            T36 = SUB(T34, T35);
            T9K = ADD(T34, T35);
          }
          T37 = SUB(T33, T36);
          Tc3 = ADD(T9J, T9K);
          T55 = ADD(T33, T36);
          T9L = SUB(T9J, T9K);
        }
        {
          E T2U, TaG, T2X, TaH;
          {
            E T2S, T2T, T2V, T2W;
            T2S = R1[WS(rs, 40)];
            T2T = R1[WS(rs, 10)];
            T2U = SUB(T2S, T2T);
            TaG = ADD(T2S, T2T);
            T2V = R1[WS(rs, 55)];
            T2W = R1[WS(rs, 25)];
            T2X = SUB(T2V, T2W);
            TaH = ADD(T2V, T2W);
          }
          T2Y = SUB(T2U, T2X);
          TcD = ADD(TaH, TaG);
          T5U = ADD(T2X, T2U);
          TaI = SUB(TaG, TaH);
        }
        {
          E T9M, T16, T9F, TaL, TaJ, TaK;
          T9M = SUB(T9I, T9L);
          T16 = ADD(TY, T15);
          T9F = FNMS(KP500000000, T16, TR);
          T17 = ADD(TR, T16);
          Tab = FMA(KP866025403, T9M, T9F);
          T9N = FNMS(KP866025403, T9M, T9F);
          TaL = SUB(T15, TY);
          TaJ = ADD(T9L, T9I);
          TaK = FMA(KP500000000, TaJ, TaI);
          TaM = FNMS(KP866025403, TaL, TaK);
          TbB = SUB(TaJ, TaI);
          Tbc = FMA(KP866025403, TaL, TaK);
        }
        {
          E Tc4, Tc7, TdC, TdD;
          TcE = SUB(TcC, TcD);
          Tc4 = SUB(Tc2, Tc3);
          Tc7 = SUB(Tc5, Tc6);
          TcF = ADD(Tc4, Tc7);
          Tc8 = SUB(Tc4, Tc7);
          TcG = FNMS(KP500000000, TcF, TcE);
          TdB = ADD(TcC, TcD);
          TdC = ADD(Tc2, Tc3);
          TdD = ADD(Tc5, Tc6);
          TdE = ADD(TdC, TdD);
          TdF = FNMS(KP500000000, TdE, TdB);
          Teb = SUB(TdD, TdC);
        }
        {
          E T2Z, T38, T3h, T3i;
          T2Z = FNMS(KP707106781, T2Y, T2R);
          T38 = FMA(KP707106781, T37, T30);
          T3h = FMA(KP707106781, T3g, T39);
          T3i = ADD(T38, T3h);
          T3j = ADD(T2Z, T3i);
          T8u = FNMS(KP500000000, T3i, T2Z);
          T7C = SUB(T3h, T38);
        }
        {
          E T5V, T56, T59, T5W;
          T5V = FNMS(KP707106781, T5U, T5T);
          T56 = FNMS(KP707106781, T55, T54);
          T59 = FNMS(KP707106781, T58, T57);
          T5W = ADD(T56, T59);
          T5a = SUB(T56, T59);
          T6Y = ADD(T5V, T5W);
          T5X = FNMS(KP500000000, T5W, T5V);
        }
        {
          E T7x, T7y, T7z, T7A;
          T7x = FMA(KP707106781, T5U, T5T);
          T7y = FMA(KP707106781, T55, T54);
          T7z = FMA(KP707106781, T58, T57);
          T7A = ADD(T7y, T7z);
          T7B = FNMS(KP500000000, T7A, T7x);
          T8v = SUB(T7z, T7y);
          T87 = ADD(T7x, T7A);
        }
        {
          E T4t, T4u, T4v, T4w;
          T4t = FMA(KP707106781, T2Y, T2R);
          T4u = FNMS(KP707106781, T37, T30);
          T4v = FNMS(KP707106781, T3g, T39);
          T4w = ADD(T4u, T4v);
          T4x = ADD(T4t, T4w);
          T5Y = SUB(T4v, T4u);
          T53 = FNMS(KP500000000, T4w, T4t);
        }
      }
      {
        E T1f, TcI, T3l, T61, T1m, Tca, T3u, T5e, T1t, Tcd, T3D, T5h,
         T3K, Tce, T5i;
        E T9S, T3B, Tcb, T5f, T9V, T3s, TcJ, T62, Tam;
        {
          E T19, T1a, T1b, T1c, T1d, T1e;
          T19 = R0[WS(rs, 24)];
          T1a = R0[WS(rs, 54)];
          T1b = ADD(T19, T1a);
          T1c = R0[WS(rs, 39)];
          T1d = R0[WS(rs, 9)];
          T1e = ADD(T1c, T1d);
          T1f = SUB(T1b, T1e);
          TcI = ADD(T1b, T1e);
          T3l = SUB(T1c, T1d);
          T61 = SUB(T19, T1a);
        }
        {
          E T1g, T1h, T1i, T1j, T1k, T1l;
          T1g = R0[WS(rs, 44)];
          T1h = R0[WS(rs, 14)];
          T1i = ADD(T1g, T1h);
          T1j = R0[WS(rs, 59)];
          T1k = R0[WS(rs, 29)];
          T1l = ADD(T1j, T1k);
          T1m = SUB(T1i, T1l);
          Tca = ADD(T1i, T1l);
          T3u = SUB(T1j, T1k);
          T5e = SUB(T1g, T1h);
        }
        {
          E T1n, T1o, T1p, T1q, T1r, T1s;
          T1n = R0[WS(rs, 4)];
          T1o = R0[WS(rs, 34)];
          T1p = ADD(T1n, T1o);
          T1q = R0[WS(rs, 19)];
          T1r = R0[WS(rs, 49)];
          T1s = ADD(T1q, T1r);
          T1t = SUB(T1p, T1s);
          Tcd = ADD(T1p, T1s);
          T3D = SUB(T1q, T1r);
          T5h = SUB(T1n, T1o);
        }
        {
          E T3G, T9Q, T3J, T9R;
          {
            E T3E, T3F, T3H, T3I;
            T3E = R1[WS(rs, 11)];
            T3F = R1[WS(rs, 41)];
            T3G = SUB(T3E, T3F);
            T9Q = ADD(T3E, T3F);
            T3H = R1[WS(rs, 56)];
            T3I = R1[WS(rs, 26)];
            T3J = SUB(T3H, T3I);
            T9R = ADD(T3H, T3I);
          }
          T3K = SUB(T3G, T3J);
          Tce = ADD(T9Q, T9R);
          T5i = ADD(T3G, T3J);
          T9S = SUB(T9Q, T9R);
        }
        {
          E T3x, T9T, T3A, T9U;
          {
            E T3v, T3w, T3y, T3z;
            T3v = R1[WS(rs, 51)];
            T3w = R1[WS(rs, 21)];
            T3x = SUB(T3v, T3w);
            T9T = ADD(T3v, T3w);
            T3y = R1[WS(rs, 36)];
            T3z = R1[WS(rs, 6)];
            T3A = SUB(T3y, T3z);
            T9U = ADD(T3y, T3z);
          }
          T3B = SUB(T3x, T3A);
          Tcb = ADD(T9T, T9U);
          T5f = ADD(T3x, T3A);
          T9V = SUB(T9T, T9U);
        }
        {
          E T3o, Tak, T3r, Tal;
          {
            E T3m, T3n, T3p, T3q;
            T3m = R1[WS(rs, 16)];
            T3n = R1[WS(rs, 46)];
            T3o = SUB(T3m, T3n);
            Tak = ADD(T3m, T3n);
            T3p = R1[WS(rs, 31)];
            T3q = R1[WS(rs, 1)];
            T3r = SUB(T3p, T3q);
            Tal = ADD(T3p, T3q);
          }
          T3s = SUB(T3o, T3r);
          TcJ = ADD(Tal, Tak);
          T62 = ADD(T3r, T3o);
          Tam = SUB(Tak, Tal);
        }
        {
          E T9W, T1u, T9P, Tap, Tan, Tao;
          T9W = SUB(T9S, T9V);
          T1u = ADD(T1m, T1t);
          T9P = FNMS(KP500000000, T1u, T1f);
          T1v = ADD(T1f, T1u);
          Tad = FMA(KP866025403, T9W, T9P);
          T9X = FNMS(KP866025403, T9W, T9P);
          Tap = SUB(T1t, T1m);
          Tan = ADD(T9V, T9S);
          Tao = FMA(KP500000000, Tan, Tam);
          Taq = FNMS(KP866025403, Tap, Tao);
          TbD = SUB(Tan, Tam);
          Tbf = FMA(KP866025403, Tap, Tao);
        }
        {
          E Tcc, Tcf, TdI, TdJ;
          TcK = SUB(TcI, TcJ);
          Tcc = SUB(Tca, Tcb);
          Tcf = SUB(Tcd, Tce);
          TcL = ADD(Tcc, Tcf);
          Tcg = SUB(Tcc, Tcf);
          TcM = FNMS(KP500000000, TcL, TcK);
          TdH = ADD(TcI, TcJ);
          TdI = ADD(Tca, Tcb);
          TdJ = ADD(Tcd, Tce);
          TdK = ADD(TdI, TdJ);
          TdL = FNMS(KP500000000, TdK, TdH);
          Te9 = SUB(TdJ, TdI);
        }
        {
          E T3t, T3C, T3L, T3M;
          T3t = FNMS(KP707106781, T3s, T3l);
          T3C = FMA(KP707106781, T3B, T3u);
          T3L = FMA(KP707106781, T3K, T3D);
          T3M = ADD(T3C, T3L);
          T3N = ADD(T3t, T3M);
          T8E = FNMS(KP500000000, T3M, T3t);
          T7K = SUB(T3L, T3C);
        }
        {
          E T63, T5g, T5j, T64;
          T63 = FNMS(KP707106781, T62, T61);
          T5g = FNMS(KP707106781, T5f, T5e);
          T5j = FNMS(KP707106781, T5i, T5h);
          T64 = ADD(T5g, T5j);
          T5k = SUB(T5g, T5j);
          T71 = ADD(T63, T64);
          T65 = FNMS(KP500000000, T64, T63);
        }
        {
          E T7F, T7G, T7H, T7I;
          T7F = FMA(KP707106781, T62, T61);
          T7G = FMA(KP707106781, T5f, T5e);
          T7H = FMA(KP707106781, T5i, T5h);
          T7I = ADD(T7G, T7H);
          T7J = FNMS(KP500000000, T7I, T7F);
          T8F = SUB(T7H, T7G);
          T89 = ADD(T7F, T7I);
        }
        {
          E T4z, T4A, T4B, T4C;
          T4z = FMA(KP707106781, T3s, T3l);
          T4A = FNMS(KP707106781, T3B, T3u);
          T4B = FNMS(KP707106781, T3K, T3D);
          T4C = ADD(T4A, T4B);
          T4D = ADD(T4z, T4C);
          T66 = SUB(T4B, T4A);
          T5d = FNMS(KP500000000, T4C, T4z);
        }
      }
      {
        E TbG, TbI, Tn, T1U, Tbx, Tby, TbH, Tbz;
        {
          E TbC, TbF, T18, T1T;
          TbC = SUB(TbA, TbB);
          TbF = SUB(TbD, TbE);
          TbG = FMA(KP618033988, TbF, TbC);
          TbI = FNMS(KP618033988, TbC, TbF);
          Tn = ADD(T7, Tm);
          T18 = ADD(TK, T17);
          T1T = ADD(T1v, T1S);
          T1U = ADD(T18, T1T);
          Tbx = FNMS(KP250000000, T1U, Tn);
          Tby = SUB(T18, T1T);
        }
        Cr[WS(csr, 30)] = ADD(Tn, T1U);
        TbH = FNMS(KP559016994, Tby, Tbx);
        Cr[WS(csr, 18)] = FNMS(KP951056516, TbI, TbH);
        Cr[WS(csr, 42)] = FMA(KP951056516, TbI, TbH);
        Tbz = FMA(KP559016994, Tby, Tbx);
        Cr[WS(csr, 54)] = FNMS(KP951056516, TbG, Tbz);
        Cr[WS(csr, 6)] = FMA(KP951056516, TbG, Tbz);
      }
      {
        E TbS, TbU, TbJ, TbM, TbN, TbO, TbT, TbP;
        {
          E TbQ, TbR, TbK, TbL;
          TbQ = SUB(TK, T17);
          TbR = SUB(T1v, T1S);
          TbS = FMA(KP618033988, TbR, TbQ);
          TbU = FNMS(KP618033988, TbQ, TbR);
          TbJ = ADD(TaT, TaU);
          TbK = ADD(TbA, TbB);
          TbL = ADD(TbD, TbE);
          TbM = ADD(TbK, TbL);
          TbN = FMA(KP250000000, TbM, TbJ);
          TbO = SUB(TbK, TbL);
        }
        Ci[WS(csi, 30)] = SUB(TbM, TbJ);
        TbT = FMA(KP559016994, TbO, TbN);
        Ci[WS(csi, 18)] = FNMS(KP951056516, TbU, TbT);
        Ci[WS(csi, 42)] = FMA(KP951056516, TbU, TbT);
        TbP = FNMS(KP559016994, TbO, TbN);
        Ci[WS(csi, 6)] = NEG(FMA(KP951056516, TbS, TbP));
        Ci[WS(csi, 54)] = NEG(FNMS(KP951056516, TbS, TbP));
      }
      {
        E T8c, T8e, T2n, T4i, T83, T84, T8d, T85;
        {
          E T88, T8b, T3k, T4h;
          T88 = SUB(T86, T87);
          T8b = SUB(T89, T8a);
          T8c = FMA(KP618033988, T8b, T88);
          T8e = FNMS(KP618033988, T88, T8b);
          T2n = ADD(T23, T2m);
          T3k = ADD(T2Q, T3j);
          T4h = ADD(T3N, T4g);
          T4i = ADD(T3k, T4h);
          T83 = FNMS(KP250000000, T4i, T2n);
          T84 = SUB(T3k, T4h);
        }
        Ci[WS(csi, 15)] = ADD(T2n, T4i);
        T8d = FNMS(KP559016994, T84, T83);
        Ci[WS(csi, 33)] = NEG(FMA(KP951056516, T8e, T8d));
        Ci[WS(csi, 57)] = NEG(FNMS(KP951056516, T8e, T8d));
        T85 = FMA(KP559016994, T84, T83);
        Ci[WS(csi, 9)] = NEG(FNMS(KP951056516, T8c, T85));
        Ci[WS(csi, 39)] = FMA(KP951056516, T8c, T85);
      }
      {
        E T8o, T8q, T8f, T8i, T8j, T8k, T8p, T8l;
        {
          E T8m, T8n, T8g, T8h;
          T8m = SUB(T3j, T2Q);
          T8n = SUB(T4g, T3N);
          T8o = FMA(KP618033988, T8n, T8m);
          T8q = FNMS(KP618033988, T8m, T8n);
          T8f = ADD(T7j, T7m);
          T8g = ADD(T86, T87);
          T8h = ADD(T89, T8a);
          T8i = ADD(T8g, T8h);
          T8j = FNMS(KP250000000, T8i, T8f);
          T8k = SUB(T8g, T8h);
        }
        Cr[WS(csr, 15)] = ADD(T8f, T8i);
        T8p = FNMS(KP559016994, T8k, T8j);
        Cr[WS(csr, 33)] = FMA(KP951056516, T8q, T8p);
        Cr[WS(csr, 57)] = FNMS(KP951056516, T8q, T8p);
        T8l = FMA(KP559016994, T8k, T8j);
        Cr[WS(csr, 9)] = FNMS(KP951056516, T8o, T8l);
        Cr[WS(csr, 39)] = FMA(KP951056516, T8o, T8l);
      }
      {
        E T74, T76, T4n, T4K, T6V, T6W, T75, T6X;
        {
          E T70, T73, T4y, T4J;
          T70 = SUB(T6Y, T6Z);
          T73 = SUB(T71, T72);
          T74 = FNMS(KP618033988, T73, T70);
          T76 = FMA(KP618033988, T70, T73);
          T4n = ADD(T4j, T4m);
          T4y = ADD(T4s, T4x);
          T4J = ADD(T4D, T4I);
          T4K = ADD(T4y, T4J);
          T6V = FNMS(KP250000000, T4K, T4n);
          T6W = SUB(T4y, T4J);
        }
        Ci[WS(csi, 45)] = NEG(ADD(T4n, T4K));
        T75 = FNMS(KP559016994, T6W, T6V);
        Ci[WS(csi, 3)] = FNMS(KP951056516, T76, T75);
        Ci[WS(csi, 27)] = FMA(KP951056516, T76, T75);
        T6X = FMA(KP559016994, T6W, T6V);
        Ci[WS(csi, 21)] = NEG(FNMS(KP951056516, T74, T6X));
        Ci[WS(csi, 51)] = FMA(KP951056516, T74, T6X);
      }
      {
        E T7g, T7i, T77, T7a, T7b, T7c, T7h, T7d;
        {
          E T7e, T7f, T78, T79;
          T7e = SUB(T4D, T4I);
          T7f = SUB(T4s, T4x);
          T7g = FNMS(KP618033988, T7f, T7e);
          T7i = FMA(KP618033988, T7e, T7f);
          T77 = ADD(T5H, T5I);
          T78 = ADD(T6Z, T6Y);
          T79 = ADD(T71, T72);
          T7a = ADD(T78, T79);
          T7b = FNMS(KP250000000, T7a, T77);
          T7c = SUB(T78, T79);
        }
        Cr[WS(csr, 45)] = ADD(T77, T7a);
        T7h = FMA(KP559016994, T7c, T7b);
        Cr[WS(csr, 21)] = FNMS(KP951056516, T7i, T7h);
        Cr[WS(csr, 51)] = FMA(KP951056516, T7i, T7h);
        T7d = FNMS(KP559016994, T7c, T7b);
        Cr[WS(csr, 3)] = FMA(KP951056516, T7g, T7d);
        Cr[WS(csr, 27)] = FNMS(KP951056516, T7g, T7d);
      }
      {
        E TaO, TaQ, T9v, Ta8, Tah, Tai, TaP, Taj;
        {
          E Tay, TaN, T9O, Ta7;
          Tay = SUB(Taq, Tax);
          TaN = SUB(TaF, TaM);
          TaO = FNMS(KP618033988, TaN, Tay);
          TaQ = FMA(KP618033988, Tay, TaN);
          T9v = FNMS(KP866025403, T9u, T9n);
          T9O = ADD(T9E, T9N);
          Ta7 = ADD(T9X, Ta6);
          Ta8 = ADD(T9O, Ta7);
          Tah = FNMS(KP250000000, Ta8, T9v);
          Tai = SUB(T9O, Ta7);
        }
        Cr[WS(csr, 50)] = ADD(T9v, Ta8);
        TaP = FMA(KP559016994, Tai, Tah);
        Cr[WS(csr, 46)] = FNMS(KP951056516, TaQ, TaP);
        Cr[WS(csr, 26)] = FMA(KP951056516, TaQ, TaP);
        Taj = FNMS(KP559016994, Tai, Tah);
        Cr[WS(csr, 2)] = FNMS(KP951056516, TaO, Taj);
        Cr[WS(csr, 22)] = FMA(KP951056516, TaO, Taj);
      }
      {
        E Tb6, Tb8, TaX, Tb0, Tb1, Tb2, Tb7, Tb3;
        {
          E Tb4, Tb5, TaY, TaZ;
          Tb4 = SUB(T9X, Ta6);
          Tb5 = SUB(T9N, T9E);
          Tb6 = FMA(KP618033988, Tb5, Tb4);
          Tb8 = FNMS(KP618033988, Tb4, Tb5);
          TaX = FNMS(KP866025403, TaW, TaV);
          TaY = ADD(TaF, TaM);
          TaZ = ADD(Taq, Tax);
          Tb0 = ADD(TaY, TaZ);
          Tb1 = FNMS(KP250000000, Tb0, TaX);
          Tb2 = SUB(TaY, TaZ);
        }
        Ci[WS(csi, 50)] = ADD(TaX, Tb0);
        Tb7 = FMA(KP559016994, Tb2, Tb1);
        Ci[WS(csi, 46)] = NEG(FNMS(KP951056516, Tb8, Tb7));
        Ci[WS(csi, 26)] = FMA(KP951056516, Tb8, Tb7);
        Tb3 = FNMS(KP559016994, Tb2, Tb1);
        Ci[WS(csi, 22)] = NEG(FNMS(KP951056516, Tb6, Tb3));
        Ci[WS(csi, 2)] = FMA(KP951056516, Tb6, Tb3);
      }
      {
        E Tbi, Tbk, Ta9, Tag, Tb9, Tba, Tbj, Tbb;
        {
          E Tbe, Tbh, Tac, Taf;
          Tbe = SUB(Tbc, Tbd);
          Tbh = SUB(Tbf, Tbg);
          Tbi = FNMS(KP618033988, Tbh, Tbe);
          Tbk = FMA(KP618033988, Tbe, Tbh);
          Ta9 = FMA(KP866025403, T9u, T9n);
          Tac = ADD(Taa, Tab);
          Taf = ADD(Tad, Tae);
          Tag = ADD(Tac, Taf);
          Tb9 = FNMS(KP250000000, Tag, Ta9);
          Tba = SUB(Tac, Taf);
        }
        Cr[WS(csr, 10)] = ADD(Ta9, Tag);
        Tbj = FNMS(KP559016994, Tba, Tb9);
        Cr[WS(csr, 38)] = FNMS(KP951056516, Tbk, Tbj);
        Cr[WS(csr, 58)] = FMA(KP951056516, Tbk, Tbj);
        Tbb = FMA(KP559016994, Tba, Tb9);
        Cr[WS(csr, 14)] = FNMS(KP951056516, Tbi, Tbb);
        Cr[WS(csr, 34)] = FMA(KP951056516, Tbi, Tbb);
      }
      {
        E Tbu, Tbw, Tbl, Tbo, Tbp, Tbq, Tbv, Tbr;
        {
          E Tbs, Tbt, Tbm, Tbn;
          Tbs = SUB(Taa, Tab);
          Tbt = SUB(Tae, Tad);
          Tbu = FNMS(KP618033988, Tbt, Tbs);
          Tbw = FMA(KP618033988, Tbs, Tbt);
          Tbl = FMA(KP866025403, TaW, TaV);
          Tbm = ADD(Tbd, Tbc);
          Tbn = ADD(Tbf, Tbg);
          Tbo = ADD(Tbm, Tbn);
          Tbp = FNMS(KP250000000, Tbo, Tbl);
          Tbq = SUB(Tbn, Tbm);
        }
        Ci[WS(csi, 10)] = ADD(Tbl, Tbo);
        Tbv = FMA(KP559016994, Tbq, Tbp);
        Ci[WS(csi, 38)] = NEG(FNMS(KP951056516, Tbw, Tbv));
        Ci[WS(csi, 58)] = FMA(KP951056516, Tbw, Tbv);
        Tbr = FNMS(KP559016994, Tbq, Tbp);
        Ci[WS(csi, 14)] = NEG(FNMS(KP951056516, Tbu, Tbr));
        Ci[WS(csi, 34)] = FMA(KP951056516, Tbu, Tbr);
      }
      {
        E Tdc, Tde, Td3, Td6, Td7, Td8, Tdd, Td9;
        {
          E Tda, Tdb, Td4, Td5;
          Tda = SUB(Tc8, Tc1);
          Tdb = SUB(Tcn, Tcg);
          Tdc = FMA(KP618033988, Tdb, Tda);
          Tde = FNMS(KP618033988, Tda, Tdb);
          Td3 = FNMS(KP500000000, Td2, Td1);
          Td4 = ADD(TcB, TcG);
          Td5 = ADD(TcM, TcR);
          Td6 = ADD(Td4, Td5);
          Td7 = FNMS(KP250000000, Td6, Td3);
          Td8 = SUB(Td4, Td5);
        }
        Cr[WS(csr, 20)] = ADD(Td3, Td6);
        Tdd = FNMS(KP559016994, Td8, Td7);
        Cr[WS(csr, 28)] = FMA(KP823639103, Tde, Tdd);
        Cr[WS(csr, 52)] = FNMS(KP823639103, Tde, Tdd);
        Td9 = FMA(KP559016994, Td8, Td7);
        Cr[WS(csr, 4)] = FNMS(KP823639103, Tdc, Td9);
        Cr[WS(csr, 44)] = FMA(KP823639103, Tdc, Td9);
      }
      {
        E TcT, TcX, Tcw, Tcp, TcU, TcV, TcY, TcW;
        {
          E TcH, TcS, Tc9, Tco;
          TcH = SUB(TcB, TcG);
          TcS = SUB(TcM, TcR);
          TcT = FMA(KP618033988, TcS, TcH);
          TcX = FNMS(KP618033988, TcH, TcS);
          Tcw = SUB(Tcs, Tcv);
          Tc9 = ADD(Tc1, Tc8);
          Tco = ADD(Tcg, Tcn);
          Tcp = ADD(Tc9, Tco);
          TcU = FMA(KP250000000, Tcp, Tcw);
          TcV = SUB(Tco, Tc9);
        }
        Ci[WS(csi, 20)] = MUL(KP866025403, SUB(Tcp, Tcw));
        TcY = FNMS(KP559016994, TcV, TcU);
        Ci[WS(csi, 28)] = NEG(MUL(KP951056516, FNMS(KP910592997, TcY, TcX)));
        Ci[WS(csi, 52)] = MUL(KP951056516, FMA(KP910592997, TcY, TcX));
        TcW = FMA(KP559016994, TcV, TcU);
        Ci[WS(csi, 4)] = MUL(KP951056516, FMA(KP910592997, TcW, TcT));
        Ci[WS(csi, 44)] = MUL(KP951056516, FNMS(KP910592997, TcW, TcT));
      }
      {
        E TdZ, Te1, Te0, TdV, Te2, TdY, Te3, Te4;
        TdZ = ADD(Tdr, Tdu);
        {
          E TdT, TdU, TdW, TdX;
          TdT = ADD(TdH, TdK);
          TdU = ADD(TdM, TdP);
          Te1 = ADD(TdT, TdU);
          TdW = ADD(Tdw, Tdz);
          TdX = ADD(TdB, TdE);
          Te0 = ADD(TdW, TdX);
          TdV = SUB(TdT, TdU);
          Te2 = ADD(Te0, Te1);
          TdY = SUB(TdW, TdX);
        }
        Ci[WS(csi, 48)] = NEG(MUL(KP951056516, FNMS(KP618033988, TdY, TdV)));
        Ci[WS(csi, 24)] = MUL(KP951056516, FMA(KP618033988, TdV, TdY));
        Cr[0] = ADD(TdZ, Te2);
        Te3 = FNMS(KP250000000, Te2, TdZ);
        Te4 = SUB(Te0, Te1);
        Cr[WS(csr, 24)] = FMA(KP559016994, Te4, Te3);
        Cr[WS(csr, 48)] = FNMS(KP559016994, Te4, Te3);
      }
      {
        E Tdl, Tdm, Tdn, Tdh, Tdo, Tdk, Tdp, Tdq;
        Tdl = ADD(Td1, Td2);
        {
          E Tdf, Tdg, Tdi, Tdj;
          Tdf = ADD(TcE, TcF);
          Tdg = ADD(Tcz, TcA);
          Tdm = ADD(Tdg, Tdf);
          Tdi = ADD(TcK, TcL);
          Tdj = ADD(TcP, TcQ);
          Tdn = ADD(Tdi, Tdj);
          Tdh = SUB(Tdf, Tdg);
          Tdo = ADD(Tdm, Tdn);
          Tdk = SUB(Tdi, Tdj);
        }
        Ci[WS(csi, 36)] = MUL(KP951056516, FNMS(KP618033988, Tdk, Tdh));
        Ci[WS(csi, 12)] = MUL(KP951056516, FMA(KP618033988, Tdh, Tdk));
        Cr[WS(csr, 60)] = ADD(Tdl, Tdo);
        Tdp = FNMS(KP250000000, Tdo, Tdl);
        Tdq = SUB(Tdm, Tdn);
        Cr[WS(csr, 12)] = FNMS(KP559016994, Tdq, Tdp);
        Cr[WS(csr, 36)] = FMA(KP559016994, Tdq, Tdp);
      }
      {
        E Tej, Ter, Tek, Ten, Teo, Tep, Tes, Teq;
        {
          E Teh, Tei, Tel, Tem;
          Teh = SUB(TdL, TdQ);
          Tei = SUB(TdF, TdA);
          Tej = FMA(KP618033988, Tei, Teh);
          Ter = FNMS(KP618033988, Teh, Tei);
          Tek = SUB(Tdt, Tds);
          Tel = ADD(Tec, Teb);
          Tem = ADD(Te9, Te8);
          Ten = ADD(Tel, Tem);
          Teo = FNMS(KP250000000, Ten, Tek);
          Tep = SUB(Tel, Tem);
        }
        Ci[WS(csi, 40)] = MUL(KP866025403, ADD(Tek, Ten));
        Tes = FMA(KP559016994, Tep, Teo);
        Ci[WS(csi, 56)] = MUL(KP951056516, FNMS(KP910592997, Tes, Ter));
        Ci[WS(csi, 16)] = MUL(KP951056516, FMA(KP910592997, Tes, Ter));
        Teq = FNMS(KP559016994, Tep, Teo);
        Ci[WS(csi, 8)] = NEG(MUL(KP951056516, FMA(KP910592997, Teq, Tej)));
        Ci[WS(csi, 32)] = MUL(KP951056516, FNMS(KP910592997, Teq, Tej));
      }
      {
        E Tee, Teg, Tdv, TdS, Te5, Te6, Tef, Te7;
        {
          E Tea, Ted, TdG, TdR;
          Tea = SUB(Te8, Te9);
          Ted = SUB(Teb, Tec);
          Tee = FNMS(KP618033988, Ted, Tea);
          Teg = FMA(KP618033988, Tea, Ted);
          Tdv = FNMS(KP500000000, Tdu, Tdr);
          TdG = ADD(TdA, TdF);
          TdR = ADD(TdL, TdQ);
          TdS = ADD(TdG, TdR);
          Te5 = FNMS(KP250000000, TdS, Tdv);
          Te6 = SUB(TdG, TdR);
        }
        Cr[WS(csr, 40)] = ADD(Tdv, TdS);
        Tef = FMA(KP559016994, Te6, Te5);
        Cr[WS(csr, 16)] = FNMS(KP823639103, Teg, Tef);
        Cr[WS(csr, 56)] = FMA(KP823639103, Teg, Tef);
        Te7 = FNMS(KP559016994, Te6, Te5);
        Cr[WS(csr, 32)] = FNMS(KP823639103, Tee, Te7);
        Cr[WS(csr, 8)] = FMA(KP823639103, Tee, Te7);
      }
      {
        E T7p, T7V, T8N, T9b, T7U, T8V, T8s, T8U, T94, T9g, T97, T9e,
         T8A, T8S, T8H;
        E T8Q, T82, T9j, T90, T9i, T7n, T8L;
        T7n = FNMS(KP500000000, T7m, T7j);
        T7p = FMA(KP866025403, T7o, T7n);
        T7V = FNMS(KP866025403, T7o, T7n);
        T8L = FNMS(KP500000000, T2m, T23);
        T8N = FNMS(KP866025403, T8M, T8L);
        T9b = FMA(KP866025403, T8M, T8L);
        {
          E T7w, T7D, T7E, T7L, T7S, T7T;
          T7w = FMA(KP866025403, T7v, T7u);
          T7D = FMA(KP866025403, T7C, T7B);
          T7E = ADD(T7w, T7D);
          T7L = FMA(KP866025403, T7K, T7J);
          T7S = FMA(KP866025403, T7R, T7Q);
          T7T = ADD(T7L, T7S);
          T7U = ADD(T7E, T7T);
          T8V = SUB(T7L, T7S);
          T8s = SUB(T7E, T7T);
          T8U = SUB(T7w, T7D);
        }
        {
          E T92, T93, T9d, T95, T96, T9c;
          T92 = FMA(KP866025403, T8F, T8E);
          T93 = FMA(KP866025403, T8C, T8B);
          T9d = ADD(T92, T93);
          T95 = FMA(KP866025403, T8y, T8x);
          T96 = FMA(KP866025403, T8v, T8u);
          T9c = ADD(T95, T96);
          T94 = SUB(T92, T93);
          T9g = SUB(T9c, T9d);
          T97 = SUB(T95, T96);
          T9e = ADD(T9c, T9d);
        }
        {
          E T8w, T8z, T8O, T8D, T8G, T8P;
          T8w = FNMS(KP866025403, T8v, T8u);
          T8z = FNMS(KP866025403, T8y, T8x);
          T8O = ADD(T8z, T8w);
          T8D = FNMS(KP866025403, T8C, T8B);
          T8G = FNMS(KP866025403, T8F, T8E);
          T8P = ADD(T8G, T8D);
          T8A = SUB(T8w, T8z);
          T8S = SUB(T8P, T8O);
          T8H = SUB(T8D, T8G);
          T8Q = ADD(T8O, T8P);
        }
        {
          E T7W, T7X, T7Y, T7Z, T80, T81;
          T7W = FNMS(KP866025403, T7v, T7u);
          T7X = FNMS(KP866025403, T7C, T7B);
          T7Y = ADD(T7W, T7X);
          T7Z = FNMS(KP866025403, T7K, T7J);
          T80 = FNMS(KP866025403, T7R, T7Q);
          T81 = ADD(T7Z, T80);
          T82 = ADD(T7Y, T81);
          T9j = SUB(T7X, T7W);
          T90 = SUB(T7Y, T81);
          T9i = SUB(T7Z, T80);
        }
        Cr[WS(csr, 25)] = ADD(T7p, T7U);
        Ci[WS(csi, 25)] = NEG(ADD(T8N, T8Q));
        Cr[WS(csr, 55)] = ADD(T7V, T82);
        Ci[WS(csi, 55)] = ADD(T9b, T9e);
        {
          E T8I, T8K, T8t, T8J, T8r;
          T8I = FMA(KP618033988, T8H, T8A);
          T8K = FNMS(KP618033988, T8A, T8H);
          T8r = FNMS(KP250000000, T7U, T7p);
          T8t = FMA(KP559016994, T8s, T8r);
          T8J = FNMS(KP559016994, T8s, T8r);
          Cr[WS(csr, 49)] = FNMS(KP951056516, T8I, T8t);
          Cr[WS(csr, 47)] = FMA(KP951056516, T8K, T8J);
          Cr[WS(csr, 1)] = FMA(KP951056516, T8I, T8t);
          Cr[WS(csr, 23)] = FNMS(KP951056516, T8K, T8J);
        }
        {
          E T8W, T8Y, T8T, T8X, T8R;
          T8W = FMA(KP618033988, T8V, T8U);
          T8Y = FNMS(KP618033988, T8U, T8V);
          T8R = FNMS(KP250000000, T8Q, T8N);
          T8T = FNMS(KP559016994, T8S, T8R);
          T8X = FMA(KP559016994, T8S, T8R);
          Ci[WS(csi, 1)] = NEG(FMA(KP951056516, T8W, T8T));
          Ci[WS(csi, 47)] = FMA(KP951056516, T8Y, T8X);
          Ci[WS(csi, 49)] = NEG(FNMS(KP951056516, T8W, T8T));
          Ci[WS(csi, 23)] = FNMS(KP951056516, T8Y, T8X);
        }
        {
          E T98, T9a, T91, T99, T8Z;
          T98 = FNMS(KP618033988, T97, T94);
          T9a = FMA(KP618033988, T94, T97);
          T8Z = FNMS(KP250000000, T82, T7V);
          T91 = FNMS(KP559016994, T90, T8Z);
          T99 = FMA(KP559016994, T90, T8Z);
          Cr[WS(csr, 7)] = FNMS(KP951056516, T98, T91);
          Cr[WS(csr, 31)] = FMA(KP951056516, T9a, T99);
          Cr[WS(csr, 17)] = FMA(KP951056516, T98, T91);
          Cr[WS(csr, 41)] = FNMS(KP951056516, T9a, T99);
        }
        {
          E T9k, T9m, T9h, T9l, T9f;
          T9k = FMA(KP618033988, T9j, T9i);
          T9m = FNMS(KP618033988, T9i, T9j);
          T9f = FNMS(KP250000000, T9e, T9b);
          T9h = FNMS(KP559016994, T9g, T9f);
          T9l = FMA(KP559016994, T9g, T9f);
          Ci[WS(csi, 17)] = NEG(FNMS(KP951056516, T9k, T9h));
          Ci[WS(csi, 31)] = FMA(KP951056516, T9m, T9l);
          Ci[WS(csi, 7)] = FMA(KP951056516, T9k, T9h);
          Ci[WS(csi, 41)] = NEG(FNMS(KP951056516, T9m, T9l));
        }
      }
      {
        E T4T, T5x, T5L, T6J, T5w, T6q, T6k, T6l, T6C, T6O, T6F, T6M,
         T6g, T6t, T6i;
        E T6s, T5E, T6R, T6y, T6Q, T4L, T5J;
        T4L = FNMS(KP500000000, T4m, T4j);
        T4T = FMA(KP866025403, T4S, T4L);
        T5x = FNMS(KP866025403, T4S, T4L);
        T5J = FNMS(KP500000000, T5I, T5H);
        T5L = FNMS(KP866025403, T5K, T5J);
        T6J = FMA(KP866025403, T5K, T5J);
        {
          E T52, T5b, T5c, T5l, T5u, T5v;
          T52 = FNMS(KP866025403, T51, T4U);
          T5b = FNMS(KP866025403, T5a, T53);
          T5c = ADD(T52, T5b);
          T5l = FNMS(KP866025403, T5k, T5d);
          T5u = FNMS(KP866025403, T5t, T5m);
          T5v = ADD(T5l, T5u);
          T5w = ADD(T5c, T5v);
          T6q = SUB(T5c, T5v);
          T6k = SUB(T52, T5b);
          T6l = SUB(T5u, T5l);
        }
        {
          E T6A, T6B, T6K, T6D, T6E, T6L;
          T6A = FMA(KP866025403, T5R, T5Q);
          T6B = FMA(KP866025403, T5Y, T5X);
          T6K = ADD(T6A, T6B);
          T6D = FMA(KP866025403, T66, T65);
          T6E = FMA(KP866025403, T6d, T6c);
          T6L = ADD(T6D, T6E);
          T6C = SUB(T6A, T6B);
          T6O = SUB(T6K, T6L);
          T6F = SUB(T6D, T6E);
          T6M = ADD(T6K, T6L);
        }
        {
          E T5S, T5Z, T60, T67, T6e, T6f;
          T5S = FNMS(KP866025403, T5R, T5Q);
          T5Z = FNMS(KP866025403, T5Y, T5X);
          T60 = ADD(T5S, T5Z);
          T67 = FNMS(KP866025403, T66, T65);
          T6e = FNMS(KP866025403, T6d, T6c);
          T6f = ADD(T67, T6e);
          T6g = ADD(T60, T6f);
          T6t = SUB(T6e, T67);
          T6i = SUB(T60, T6f);
          T6s = SUB(T5S, T5Z);
        }
        {
          E T5y, T5z, T5A, T5B, T5C, T5D;
          T5y = FMA(KP866025403, T51, T4U);
          T5z = FMA(KP866025403, T5a, T53);
          T5A = ADD(T5y, T5z);
          T5B = FMA(KP866025403, T5k, T5d);
          T5C = FMA(KP866025403, T5t, T5m);
          T5D = ADD(T5B, T5C);
          T5E = ADD(T5A, T5D);
          T6R = SUB(T5B, T5C);
          T6y = SUB(T5A, T5D);
          T6Q = SUB(T5y, T5z);
        }
        Ci[WS(csi, 5)] = NEG(ADD(T4T, T5w));
        Cr[WS(csr, 5)] = ADD(T5L, T6g);
        Ci[WS(csi, 35)] = ADD(T5x, T5E);
        Cr[WS(csr, 35)] = ADD(T6J, T6M);
        {
          E T6m, T6o, T6j, T6n, T6h;
          T6m = FNMS(KP618033988, T6l, T6k);
          T6o = FMA(KP618033988, T6k, T6l);
          T6h = FNMS(KP250000000, T6g, T5L);
          T6j = FMA(KP559016994, T6i, T6h);
          T6n = FNMS(KP559016994, T6i, T6h);
          Cr[WS(csr, 19)] = FNMS(KP951056516, T6m, T6j);
          Cr[WS(csr, 53)] = FMA(KP951056516, T6o, T6n);
          Cr[WS(csr, 29)] = FMA(KP951056516, T6m, T6j);
          Cr[WS(csr, 43)] = FNMS(KP951056516, T6o, T6n);
        }
        {
          E T6u, T6w, T6r, T6v, T6p;
          T6u = FNMS(KP618033988, T6t, T6s);
          T6w = FMA(KP618033988, T6s, T6t);
          T6p = FNMS(KP250000000, T5w, T4T);
          T6r = FMA(KP559016994, T6q, T6p);
          T6v = FNMS(KP559016994, T6q, T6p);
          Ci[WS(csi, 19)] = FMA(KP951056516, T6u, T6r);
          Ci[WS(csi, 53)] = NEG(FNMS(KP951056516, T6w, T6v));
          Ci[WS(csi, 29)] = NEG(FNMS(KP951056516, T6u, T6r));
          Ci[WS(csi, 43)] = FMA(KP951056516, T6w, T6v);
        }
        {
          E T6G, T6I, T6z, T6H, T6x;
          T6G = FMA(KP618033988, T6F, T6C);
          T6I = FNMS(KP618033988, T6C, T6F);
          T6x = FNMS(KP250000000, T5E, T5x);
          T6z = FMA(KP559016994, T6y, T6x);
          T6H = FNMS(KP559016994, T6y, T6x);
          Ci[WS(csi, 11)] = FNMS(KP951056516, T6G, T6z);
          Ci[WS(csi, 37)] = NEG(FNMS(KP951056516, T6I, T6H));
          Ci[WS(csi, 59)] = FMA(KP951056516, T6G, T6z);
          Ci[WS(csi, 13)] = NEG(FMA(KP951056516, T6I, T6H));
        }
        {
          E T6S, T6U, T6P, T6T, T6N;
          T6S = FMA(KP618033988, T6R, T6Q);
          T6U = FNMS(KP618033988, T6Q, T6R);
          T6N = FNMS(KP250000000, T6M, T6J);
          T6P = FMA(KP559016994, T6O, T6N);
          T6T = FNMS(KP559016994, T6O, T6N);
          Cr[WS(csr, 11)] = FMA(KP951056516, T6S, T6P);
          Cr[WS(csr, 37)] = FMA(KP951056516, T6U, T6T);
          Cr[WS(csr, 59)] = FNMS(KP951056516, T6S, T6P);
          Cr[WS(csr, 13)] = FNMS(KP951056516, T6U, T6T);
        }
      }
    }
  }
}
