/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 120 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_hc2r_120 */

/*
 * This function contains 896 FP additions, 412 FP multiplications,
 * (or, 484 additions, 0 multiplications, 412 fused multiply/add),
 * 230 stack variables, 11 constants, and 240 memory accesses
 */
void dft_codelet_hc2r_120(R * R0, R * R1, const R * Cr, const R * Ci)
{
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP1_902113032, +1.902113032590307144232878666758764286811397268);
  DK(KP1_118033988, +1.118033988749894848204586834365638117720309180);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  DK(KP1_414213562, +1.414213562373095048801688724209698078569671875);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    
    {
      E T9, To, T9B, T6d, T6e, T8R, T5x, T5C, T8f, T1X, T1Y, T99, T9c,
       T9C, T2j;
      E T4l, T2A, T4m, T8k, T8S, T6y, T7e, T4G, T5i, T7y, T7Y, T4B,
       T5h, T3J, T4t;
      E Ta2, TaI, T9u, Tbk, Tdt, Te0, T53, T5p, T8K, Ta3, T92, TaH,
       Tct, TcU, Tbj;
      E TbK, T9M, TbL, T25, T26, T27, T28, T9n, T5Z, T64, T69, T6a,
       T8z, T1p, T1E;
      E T1T, T1U, T9J, T6l, T6m, T6n, T6o, T8Z, T7M, T86, T7P, T87,
       T7Q, T88, T6Y;
      E T7m, T75, T7n, T76, T7o, T40, T4u, T4h, T4v, T4i, T4w, T58,
       T5q, T5d, T5r;
      E T5e, T5s, T2S, T4o, Tad, TaF, T9l, Tbd, Tdx, Te5, T4M, T5k,
       T8x, Tae, T8X;
      E TaE, Tck, TcZ, Tbc, TbP, T9H, TbQ, T20, T21, T22, T23, T9e,
       T5I, T5N, T5S;
      E T5T, T8m, TE, TT, T18, T19, T9E, T6g, T6h, T6i, T6j, T8U, T7D,
       T81, T7G;
      E T82, T7H, T83, T6H, T7h, T6O, T7i, T6P, T7j, T39, T4p, T3q,
       T4q, T3r, T4r;
      E T4R, T5l, T4W, T5m, T4X, T5n;
      {
        E T2c, T5, T5v, T2b, T8, T2e, T2h, T5w, T2n, T8i, T6v, T8h,
         Tg, T6s, T2k;
        E T5y, Tj, T5z, Tm, T5A, Tn, T2t, T5B, T4E, T4D, T2y;
        T2c = Ci[WSCI(30)];
        {
          E T4, T1, T2, T3;
          T4 = Cr[WSCR(30)];
          T1 = Cr[0];
          T2 = Cr[WSCR(60)];
          T3 = ADD(T1, T2);
          T5 = FMA(KP2_000000000, T4, T3);
          T5v = FNMS(KP2_000000000, T4, T3);
          T2b = SUB(T1, T2);
        }
        {
          E T6, T7, T2f, T2g;
          T6 = Cr[WSCR(15)];
          T7 = Cr[WSCR(45)];
          T8 = ADD(T6, T7);
          T2e = SUB(T6, T7);
          T2f = Ci[WSCI(15)];
          T2g = Ci[WSCI(45)];
          T2h = ADD(T2f, T2g);
          T5w = SUB(T2f, T2g);
        }
        {
          E T2l, T2m, T6t, T6u;
          T2l = Ci[WSCI(50)];
          T2m = Ci[WSCI(10)];
          T2n = ADD(T2l, T2m);
          T8i = SUB(T2m, T2l);
          T6t = Ci[WSCI(40)];
          T6u = Ci[WSCI(20)];
          T6v = ADD(T6t, T6u);
          T8h = SUB(T6t, T6u);
        }
        {
          E Ta, Tb, Tc, Td, Te, Tf;
          Ta = Cr[WSCR(40)];
          Tb = Cr[WSCR(20)];
          Tc = ADD(Ta, Tb);
          Td = Cr[WSCR(50)];
          Te = Cr[WSCR(10)];
          Tf = ADD(Td, Te);
          Tg = ADD(Tc, Tf);
          T6s = SUB(Td, Te);
          T2k = SUB(Tb, Ta);
          T5y = SUB(Tf, Tc);
        }
        {
          E T2u, T2x, T2s, T2r;
          {
            E Th, Ti, T2v, T2w;
            Th = Cr[WSCR(55)];
            Ti = Cr[WSCR(5)];
            Tj = ADD(Th, Ti);
            T2u = SUB(Th, Ti);
            T2v = Ci[WSCI(55)];
            T2w = Ci[WSCI(5)];
            T2x = ADD(T2v, T2w);
            T5z = SUB(T2w, T2v);
          }
          {
            E Tk, Tl, T2p, T2q;
            Tk = Cr[WSCR(25)];
            Tl = Cr[WSCR(35)];
            Tm = ADD(Tk, Tl);
            T2s = SUB(Tk, Tl);
            T2p = Ci[WSCI(25)];
            T2q = Ci[WSCI(35)];
            T2r = ADD(T2p, T2q);
            T5A = SUB(T2p, T2q);
          }
          Tn = ADD(Tj, Tm);
          T2t = SUB(T2r, T2s);
          T5B = ADD(T5z, T5A);
          T4E = SUB(T2x, T2u);
          T4D = ADD(T2s, T2r);
          T2y = ADD(T2u, T2x);
        }
        T9 = FMA(KP2_000000000, T8, T5);
        To = ADD(Tg, Tn);
        T9B = SUB(T9, To);
        T6d = FMA(KP2_000000000, T5w, T5v);
        T6e = ADD(T5y, T5B);
        T8R = ADD(T6d, T6e);
        T5x = FNMS(KP2_000000000, T5w, T5v);
        T5C = SUB(T5y, T5B);
        T8f = ADD(T5x, T5C);
        T1X = FNMS(KP2_000000000, T8, T5);
        T1Y = SUB(Tn, Tg);
        T99 = ADD(T1X, T1Y);
        {
          E T9a, T9b, T2d, T2i;
          T9a = ADD(T8i, T8h);
          T9b = SUB(T5A, T5z);
          T9c = SUB(T9a, T9b);
          T9C = ADD(T9b, T9a);
          T2d = FMA(KP2_000000000, T2c, T2b);
          T2i = ADD(T2e, T2h);
          T2j = FMA(KP1_414213562, T2i, T2d);
          T4l = FNMS(KP1_414213562, T2i, T2d);
        }
        {
          E T2o, T2z, T4C, T4F;
          T2o = ADD(T2k, T2n);
          T2z = SUB(T2t, T2y);
          T2A = FMA(KP707106781, T2z, T2o);
          T4m = FNMS(KP707106781, T2z, T2o);
          {
            E T8g, T8j, T6w, T6x;
            T8g = SUB(Tj, Tm);
            T8j = SUB(T8h, T8i);
            T8k = ADD(T8g, T8j);
            T8S = SUB(T8j, T8g);
            T6w = ADD(T6s, T6v);
            T6x = ADD(T2y, T2t);
            T6y = FMA(KP707106781, T6x, T6w);
            T7e = FNMS(KP707106781, T6x, T6w);
          }
          T4C = SUB(T2k, T2n);
          T4F = SUB(T4D, T4E);
          T4G = FNMS(KP707106781, T4F, T4C);
          T5i = FMA(KP707106781, T4F, T4C);
          {
            E T7w, T7x, T4z, T4A;
            T7w = SUB(T6v, T6s);
            T7x = ADD(T4E, T4D);
            T7y = FNMS(KP707106781, T7x, T7w);
            T7Y = FMA(KP707106781, T7x, T7w);
            T4z = FNMS(KP2_000000000, T2c, T2b);
            T4A = SUB(T2e, T2h);
            T4B = FMA(KP1_414213562, T4A, T4z);
            T5h = FNMS(KP1_414213562, T4A, T4z);
          }
        }
      }
      {
        E T3w, Ta0, T1h, Tcp, T3t, T5V, T9Z, Tcq, T1k, T5W, T1n, T5X,
         T1o, T3C, T5Y;
        E T51, T50, T3H, T1w, T8I, T9r, T3O, T54, T73, T7N, T60, T1L,
         T8D, T9o, T45;
        E T59, T6W, T7K, T65, T1S, T8A, T9p, T4a, T4f, T5b, T68, T5a,
         T1D, T8F, T9s;
        E T3T, T3Y, T56, T63, T55;
        {
          E T3u, T3v, T9X, T9Y;
          T3u = Ci[WSCI(42)];
          T3v = Ci[WSCI(18)];
          T3w = ADD(T3u, T3v);
          Ta0 = SUB(T3v, T3u);
          {
            E T1b, T1c, T1d, T1e, T1f, T1g;
            T1b = Cr[WSCR(48)];
            T1c = Cr[WSCR(12)];
            T1d = ADD(T1b, T1c);
            T1e = Cr[WSCR(42)];
            T1f = Cr[WSCR(18)];
            T1g = ADD(T1e, T1f);
            T1h = ADD(T1d, T1g);
            Tcp = SUB(T1e, T1f);
            T3t = SUB(T1b, T1c);
            T5V = SUB(T1d, T1g);
          }
          T9X = Ci[WSCI(48)];
          T9Y = Ci[WSCI(12)];
          T9Z = SUB(T9X, T9Y);
          Tcq = ADD(T9X, T9Y);
          {
            E T3B, T3A, T3G, T3F;
            {
              E T1i, T1j, T3y, T3z;
              T1i = Cr[WSCR(57)];
              T1j = Cr[WSCR(3)];
              T1k = ADD(T1i, T1j);
              T3B = SUB(T1i, T1j);
              T3y = Ci[WSCI(57)];
              T3z = Ci[WSCI(3)];
              T3A = ADD(T3y, T3z);
              T5W = SUB(T3y, T3z);
            }
            {
              E T1l, T1m, T3D, T3E;
              T1l = Cr[WSCR(33)];
              T1m = Cr[WSCR(27)];
              T1n = ADD(T1l, T1m);
              T3G = SUB(T1l, T1m);
              T3D = Ci[WSCI(33)];
              T3E = Ci[WSCI(27)];
              T3F = ADD(T3D, T3E);
              T5X = SUB(T3D, T3E);
            }
            T1o = ADD(T1k, T1n);
            T3C = SUB(T3A, T3B);
            T5Y = ADD(T5W, T5X);
            T51 = ADD(T3G, T3F);
            T50 = ADD(T3B, T3A);
            T3H = SUB(T3F, T3G);
          }
        }
        {
          E T1s, T3K, T72, T8G, T1v, T6Z, T3N, T8H;
          {
            E T1q, T1r, T70, T71;
            T1q = Cr[WSCR(32)];
            T1r = Cr[WSCR(28)];
            T1s = ADD(T1q, T1r);
            T3K = SUB(T1r, T1q);
            T70 = Ci[WSCI(32)];
            T71 = Ci[WSCI(28)];
            T72 = ADD(T70, T71);
            T8G = SUB(T71, T70);
          }
          {
            E T1t, T1u, T3L, T3M;
            T1t = Cr[WSCR(2)];
            T1u = Cr[WSCR(58)];
            T1v = ADD(T1t, T1u);
            T6Z = SUB(T1t, T1u);
            T3L = Ci[WSCI(2)];
            T3M = Ci[WSCI(58)];
            T3N = ADD(T3L, T3M);
            T8H = SUB(T3M, T3L);
          }
          T1w = ADD(T1s, T1v);
          T8I = SUB(T8G, T8H);
          T9r = ADD(T8H, T8G);
          T3O = ADD(T3K, T3N);
          T54 = SUB(T3K, T3N);
          T73 = SUB(T6Z, T72);
          T7N = ADD(T6Z, T72);
          T60 = SUB(T1v, T1s);
        }
        {
          E T1H, T41, T6V, T8B, T1K, T6S, T44, T8C;
          {
            E T1F, T1G, T6T, T6U;
            T1F = Cr[WSCR(8)];
            T1G = Cr[WSCR(52)];
            T1H = ADD(T1F, T1G);
            T41 = SUB(T1G, T1F);
            T6T = Ci[WSCI(8)];
            T6U = Ci[WSCI(52)];
            T6V = ADD(T6T, T6U);
            T8B = SUB(T6T, T6U);
          }
          {
            E T1I, T1J, T42, T43;
            T1I = Cr[WSCR(38)];
            T1J = Cr[WSCR(22)];
            T1K = ADD(T1I, T1J);
            T6S = SUB(T1I, T1J);
            T42 = Ci[WSCI(38)];
            T43 = Ci[WSCI(22)];
            T44 = ADD(T42, T43);
            T8C = SUB(T42, T43);
          }
          T1L = ADD(T1H, T1K);
          T8D = SUB(T8B, T8C);
          T9o = ADD(T8C, T8B);
          T45 = SUB(T41, T44);
          T59 = ADD(T41, T44);
          T6W = ADD(T6S, T6V);
          T7K = SUB(T6V, T6S);
          T65 = SUB(T1K, T1H);
        }
        {
          E T1O, T46, T49, T66, T1R, T4b, T4e, T67;
          {
            E T1M, T1N, T47, T48;
            T1M = Cr[WSCR(23)];
            T1N = Cr[WSCR(37)];
            T1O = ADD(T1M, T1N);
            T46 = SUB(T1M, T1N);
            T47 = Ci[WSCI(23)];
            T48 = Ci[WSCI(37)];
            T49 = ADD(T47, T48);
            T66 = SUB(T48, T47);
          }
          {
            E T1P, T1Q, T4c, T4d;
            T1P = Cr[WSCR(7)];
            T1Q = Cr[WSCR(53)];
            T1R = ADD(T1P, T1Q);
            T4b = SUB(T1Q, T1P);
            T4c = Ci[WSCI(7)];
            T4d = Ci[WSCI(53)];
            T4e = ADD(T4c, T4d);
            T67 = SUB(T4d, T4c);
          }
          T1S = ADD(T1O, T1R);
          T8A = SUB(T1O, T1R);
          T9p = SUB(T67, T66);
          T4a = ADD(T46, T49);
          T4f = SUB(T4b, T4e);
          T5b = ADD(T4b, T4e);
          T68 = ADD(T66, T67);
          T5a = SUB(T46, T49);
        }
        {
          E T1z, T3P, T3S, T61, T1C, T3U, T3X, T62;
          {
            E T1x, T1y, T3Q, T3R;
            T1x = Cr[WSCR(17)];
            T1y = Cr[WSCR(43)];
            T1z = ADD(T1x, T1y);
            T3P = SUB(T1x, T1y);
            T3Q = Ci[WSCI(17)];
            T3R = Ci[WSCI(43)];
            T3S = ADD(T3Q, T3R);
            T61 = SUB(T3Q, T3R);
          }
          {
            E T1A, T1B, T3V, T3W;
            T1A = Cr[WSCR(47)];
            T1B = Cr[WSCR(13)];
            T1C = ADD(T1A, T1B);
            T3U = SUB(T1B, T1A);
            T3V = Ci[WSCI(47)];
            T3W = Ci[WSCI(13)];
            T3X = ADD(T3V, T3W);
            T62 = SUB(T3W, T3V);
          }
          T1D = ADD(T1z, T1C);
          T8F = SUB(T1z, T1C);
          T9s = SUB(T62, T61);
          T3T = SUB(T3P, T3S);
          T3Y = SUB(T3U, T3X);
          T56 = ADD(T3U, T3X);
          T63 = ADD(T61, T62);
          T55 = ADD(T3P, T3S);
        }
        {
          E T90, T91, T9K, T9L;
          {
            E T3x, T3I, T9W, Ta1;
            T3x = SUB(T3t, T3w);
            T3I = ADD(T3C, T3H);
            T3J = FNMS(KP707106781, T3I, T3x);
            T4t = FMA(KP707106781, T3I, T3x);
            T9W = SUB(T1k, T1n);
            Ta1 = SUB(T9Z, Ta0);
            Ta2 = ADD(T9W, Ta1);
            TaI = SUB(Ta1, T9W);
          }
          {
            E T9q, T9t, Tdr, Tds;
            T9q = SUB(T9o, T9p);
            T9t = SUB(T9r, T9s);
            T9u = SUB(T9q, T9t);
            Tbk = ADD(T9q, T9t);
            Tdr = SUB(Tcq, Tcp);
            Tds = SUB(T50, T51);
            Tdt = FMA(KP707106781, Tds, Tdr);
            Te0 = FNMS(KP707106781, Tds, Tdr);
          }
          {
            E T4Z, T52, T8E, T8J;
            T4Z = ADD(T3t, T3w);
            T52 = ADD(T50, T51);
            T53 = FMA(KP707106781, T52, T4Z);
            T5p = FNMS(KP707106781, T52, T4Z);
            T8E = ADD(T8A, T8D);
            T8J = ADD(T8F, T8I);
            T8K = SUB(T8E, T8J);
            Ta3 = ADD(T8E, T8J);
          }
          T90 = SUB(T8D, T8A);
          T91 = SUB(T8I, T8F);
          T92 = SUB(T90, T91);
          TaH = ADD(T90, T91);
          {
            E Tcr, Tcs, Tbh, Tbi;
            Tcr = ADD(Tcp, Tcq);
            Tcs = SUB(T3H, T3C);
            Tct = FMA(KP707106781, Tcs, Tcr);
            TcU = FNMS(KP707106781, Tcs, Tcr);
            Tbh = ADD(Ta0, T9Z);
            Tbi = SUB(T5X, T5W);
            Tbj = SUB(Tbh, Tbi);
            TbK = ADD(Tbi, Tbh);
          }
          T9K = ADD(T9p, T9o);
          T9L = ADD(T9s, T9r);
          T9M = SUB(T9K, T9L);
          TbL = ADD(T9K, T9L);
          T25 = SUB(T1h, T1o);
          T26 = SUB(T1D, T1w);
          T27 = SUB(T1S, T1L);
          T28 = ADD(T26, T27);
          T9n = FMA(KP2_000000000, T25, T28);
          T5Z = ADD(T5V, T5Y);
          T64 = SUB(T60, T63);
          T69 = SUB(T65, T68);
          T6a = ADD(T64, T69);
          T8z = FMA(KP2_000000000, T5Z, T6a);
          T1p = ADD(T1h, T1o);
          T1E = ADD(T1w, T1D);
          T1T = ADD(T1L, T1S);
          T1U = ADD(T1E, T1T);
          T9J = FNMS(KP2_000000000, T1p, T1U);
          {
            E T7L, T7O, T6X, T74;
            T6l = SUB(T5V, T5Y);
            T6m = ADD(T60, T63);
            T6n = ADD(T65, T68);
            T6o = ADD(T6m, T6n);
            T8Z = FMA(KP2_000000000, T6l, T6o);
            T7L = ADD(T5a, T5b);
            T7M = FMA(KP707106781, T7L, T7K);
            T86 = FNMS(KP707106781, T7L, T7K);
            T7O = ADD(T55, T56);
            T7P = FNMS(KP707106781, T7O, T7N);
            T87 = FMA(KP707106781, T7O, T7N);
            T7Q = ADD(T7M, T7P);
            T88 = ADD(T86, T87);
            T6X = ADD(T4a, T4f);
            T6Y = FMA(KP707106781, T6X, T6W);
            T7m = FNMS(KP707106781, T6X, T6W);
            T74 = ADD(T3T, T3Y);
            T75 = FMA(KP707106781, T74, T73);
            T7n = FNMS(KP707106781, T74, T73);
            T76 = SUB(T6Y, T75);
            T7o = SUB(T7m, T7n);
            {
              E T3Z, T4g, T57, T5c;
              T3Z = SUB(T3T, T3Y);
              T40 = FNMS(KP707106781, T3Z, T3O);
              T4u = FMA(KP707106781, T3Z, T3O);
              T4g = SUB(T4a, T4f);
              T4h = FNMS(KP707106781, T4g, T45);
              T4v = FMA(KP707106781, T4g, T45);
              T4i = ADD(T40, T4h);
              T4w = ADD(T4u, T4v);
              T57 = SUB(T55, T56);
              T58 = FNMS(KP707106781, T57, T54);
              T5q = FMA(KP707106781, T57, T54);
              T5c = SUB(T5a, T5b);
              T5d = FNMS(KP707106781, T5c, T59);
              T5r = FMA(KP707106781, T5c, T59);
              T5e = ADD(T58, T5d);
              T5s = ADD(T5q, T5r);
            }
          }
        }
      }
      {
        E T2F, Tab, Tw, Tcg, T2C, T5E, Taa, Tch, Tz, T5F, TC, T5G, TD,
         T2L, T5H;
        E T4K, T4J, T2Q, TL, T8v, T9i, T2X, T4N, T6M, T7B, T5J, T10,
         T8q, T9f, T3e;
        E T4S, T6F, T7E, T5O, T17, T8n, T9g, T3j, T3o, T4U, T5R, T4T,
         TS, T8s, T9j;
        E T32, T37, T4P, T5M, T4O;
        {
          E T2D, T2E, Ta8, Ta9;
          T2D = Ci[WSCI(54)];
          T2E = Ci[WSCI(6)];
          T2F = ADD(T2D, T2E);
          Tab = SUB(T2D, T2E);
          {
            E Tq, Tr, Ts, Tt, Tu, Tv;
            Tq = Cr[WSCR(24)];
            Tr = Cr[WSCR(36)];
            Ts = ADD(Tq, Tr);
            Tt = Cr[WSCR(54)];
            Tu = Cr[WSCR(6)];
            Tv = ADD(Tt, Tu);
            Tw = ADD(Ts, Tv);
            Tcg = SUB(Tt, Tu);
            T2C = SUB(Tq, Tr);
            T5E = SUB(Ts, Tv);
          }
          Ta8 = Ci[WSCI(24)];
          Ta9 = Ci[WSCI(36)];
          Taa = SUB(Ta8, Ta9);
          Tch = ADD(Ta8, Ta9);
          {
            E T2M, T2P, T2K, T2J;
            {
              E Tx, Ty, T2N, T2O;
              Tx = Cr[WSCR(39)];
              Ty = Cr[WSCR(21)];
              Tz = ADD(Tx, Ty);
              T2M = SUB(Tx, Ty);
              T2N = Ci[WSCI(39)];
              T2O = Ci[WSCI(21)];
              T2P = ADD(T2N, T2O);
              T5F = SUB(T2O, T2N);
            }
            {
              E TA, TB, T2H, T2I;
              TA = Cr[WSCR(9)];
              TB = Cr[WSCR(51)];
              TC = ADD(TA, TB);
              T2K = SUB(TA, TB);
              T2H = Ci[WSCI(9)];
              T2I = Ci[WSCI(51)];
              T2J = ADD(T2H, T2I);
              T5G = SUB(T2H, T2I);
            }
            TD = ADD(Tz, TC);
            T2L = SUB(T2J, T2K);
            T5H = ADD(T5F, T5G);
            T4K = ADD(T2K, T2J);
            T4J = SUB(T2M, T2P);
            T2Q = ADD(T2M, T2P);
          }
        }
        {
          E TH, T2T, T6L, T8t, TK, T6I, T2W, T8u;
          {
            E TF, TG, T6J, T6K;
            TF = Cr[WSCR(56)];
            TG = Cr[WSCR(4)];
            TH = ADD(TF, TG);
            T2T = SUB(TG, TF);
            T6J = Ci[WSCI(56)];
            T6K = Ci[WSCI(4)];
            T6L = ADD(T6J, T6K);
            T8t = SUB(T6K, T6J);
          }
          {
            E TI, TJ, T2U, T2V;
            TI = Cr[WSCR(26)];
            TJ = Cr[WSCR(34)];
            TK = ADD(TI, TJ);
            T6I = SUB(TI, TJ);
            T2U = Ci[WSCI(26)];
            T2V = Ci[WSCI(34)];
            T2W = ADD(T2U, T2V);
            T8u = SUB(T2V, T2U);
          }
          TL = ADD(TH, TK);
          T8v = SUB(T8t, T8u);
          T9i = ADD(T8u, T8t);
          T2X = ADD(T2T, T2W);
          T4N = SUB(T2T, T2W);
          T6M = SUB(T6I, T6L);
          T7B = ADD(T6I, T6L);
          T5J = SUB(TK, TH);
        }
        {
          E TW, T3a, T6E, T8o, TZ, T6B, T3d, T8p;
          {
            E TU, TV, T6C, T6D;
            TU = Cr[WSCR(16)];
            TV = Cr[WSCR(44)];
            TW = ADD(TU, TV);
            T3a = SUB(TV, TU);
            T6C = Ci[WSCI(16)];
            T6D = Ci[WSCI(44)];
            T6E = ADD(T6C, T6D);
            T8o = SUB(T6D, T6C);
          }
          {
            E TX, TY, T3b, T3c;
            TX = Cr[WSCR(14)];
            TY = Cr[WSCR(46)];
            TZ = ADD(TX, TY);
            T6B = SUB(TX, TY);
            T3b = Ci[WSCI(14)];
            T3c = Ci[WSCI(46)];
            T3d = ADD(T3b, T3c);
            T8p = SUB(T3b, T3c);
          }
          T10 = ADD(TW, TZ);
          T8q = SUB(T8o, T8p);
          T9f = ADD(T8p, T8o);
          T3e = SUB(T3a, T3d);
          T4S = ADD(T3a, T3d);
          T6F = SUB(T6B, T6E);
          T7E = ADD(T6B, T6E);
          T5O = SUB(TZ, TW);
        }
        {
          E T13, T3f, T3i, T5P, T16, T3k, T3n, T5Q;
          {
            E T11, T12, T3g, T3h;
            T11 = Cr[WSCR(1)];
            T12 = Cr[WSCR(59)];
            T13 = ADD(T11, T12);
            T3f = SUB(T11, T12);
            T3g = Ci[WSCI(1)];
            T3h = Ci[WSCI(59)];
            T3i = ADD(T3g, T3h);
            T5P = SUB(T3g, T3h);
          }
          {
            E T14, T15, T3l, T3m;
            T14 = Cr[WSCR(31)];
            T15 = Cr[WSCR(29)];
            T16 = ADD(T14, T15);
            T3k = SUB(T15, T14);
            T3l = Ci[WSCI(31)];
            T3m = Ci[WSCI(29)];
            T3n = ADD(T3l, T3m);
            T5Q = SUB(T3m, T3l);
          }
          T17 = ADD(T13, T16);
          T8n = SUB(T13, T16);
          T9g = SUB(T5Q, T5P);
          T3j = SUB(T3f, T3i);
          T3o = SUB(T3k, T3n);
          T4U = ADD(T3k, T3n);
          T5R = ADD(T5P, T5Q);
          T4T = ADD(T3f, T3i);
        }
        {
          E TO, T33, T36, T5K, TR, T2Y, T31, T5L;
          {
            E TM, TN, T34, T35;
            TM = Cr[WSCR(41)];
            TN = Cr[WSCR(19)];
            TO = ADD(TM, TN);
            T33 = SUB(TM, TN);
            T34 = Ci[WSCI(41)];
            T35 = Ci[WSCI(19)];
            T36 = ADD(T34, T35);
            T5K = SUB(T34, T35);
          }
          {
            E TP, TQ, T2Z, T30;
            TP = Cr[WSCR(49)];
            TQ = Cr[WSCR(11)];
            TR = ADD(TP, TQ);
            T2Y = SUB(TQ, TP);
            T2Z = Ci[WSCI(49)];
            T30 = Ci[WSCI(11)];
            T31 = ADD(T2Z, T30);
            T5L = SUB(T2Z, T30);
          }
          TS = ADD(TO, TR);
          T8s = SUB(TO, TR);
          T9j = SUB(T5L, T5K);
          T32 = ADD(T2Y, T31);
          T37 = SUB(T33, T36);
          T4P = SUB(T2Y, T31);
          T5M = ADD(T5K, T5L);
          T4O = ADD(T33, T36);
        }
        {
          E T8V, T8W, T9F, T9G;
          {
            E T2G, T2R, Ta7, Tac;
            T2G = ADD(T2C, T2F);
            T2R = SUB(T2L, T2Q);
            T2S = FNMS(KP707106781, T2R, T2G);
            T4o = FMA(KP707106781, T2R, T2G);
            Ta7 = SUB(Tz, TC);
            Tac = SUB(Taa, Tab);
            Tad = ADD(Ta7, Tac);
            TaF = SUB(Tac, Ta7);
          }
          {
            E T9h, T9k, Tdv, Tdw;
            T9h = SUB(T9f, T9g);
            T9k = SUB(T9i, T9j);
            T9l = SUB(T9h, T9k);
            Tbd = ADD(T9h, T9k);
            Tdv = SUB(Tch, Tcg);
            Tdw = SUB(T4J, T4K);
            Tdx = FMA(KP707106781, Tdw, Tdv);
            Te5 = FNMS(KP707106781, Tdw, Tdv);
          }
          {
            E T4I, T4L, T8r, T8w;
            T4I = SUB(T2C, T2F);
            T4L = ADD(T4J, T4K);
            T4M = FMA(KP707106781, T4L, T4I);
            T5k = FNMS(KP707106781, T4L, T4I);
            T8r = ADD(T8n, T8q);
            T8w = ADD(T8s, T8v);
            T8x = SUB(T8r, T8w);
            Tae = ADD(T8r, T8w);
          }
          T8V = SUB(T8q, T8n);
          T8W = SUB(T8v, T8s);
          T8X = SUB(T8V, T8W);
          TaE = ADD(T8V, T8W);
          {
            E Tci, Tcj, Tba, Tbb;
            Tci = ADD(Tcg, Tch);
            Tcj = ADD(T2Q, T2L);
            Tck = FMA(KP707106781, Tcj, Tci);
            TcZ = FNMS(KP707106781, Tcj, Tci);
            Tba = ADD(Tab, Taa);
            Tbb = SUB(T5G, T5F);
            Tbc = SUB(Tba, Tbb);
            TbP = ADD(Tbb, Tba);
          }
          T9F = ADD(T9g, T9f);
          T9G = ADD(T9j, T9i);
          T9H = SUB(T9F, T9G);
          TbQ = ADD(T9F, T9G);
          T20 = SUB(Tw, TD);
          T21 = SUB(TS, TL);
          T22 = SUB(T17, T10);
          T23 = ADD(T21, T22);
          T9e = FMA(KP2_000000000, T20, T23);
          T5I = ADD(T5E, T5H);
          T5N = SUB(T5J, T5M);
          T5S = SUB(T5O, T5R);
          T5T = ADD(T5N, T5S);
          T8m = FMA(KP2_000000000, T5I, T5T);
          TE = ADD(Tw, TD);
          TT = ADD(TL, TS);
          T18 = ADD(T10, T17);
          T19 = ADD(TT, T18);
          T9E = FNMS(KP2_000000000, TE, T19);
          {
            E T7C, T7F, T6G, T6N;
            T6g = SUB(T5E, T5H);
            T6h = ADD(T5J, T5M);
            T6i = ADD(T5O, T5R);
            T6j = ADD(T6h, T6i);
            T8U = FMA(KP2_000000000, T6g, T6j);
            T7C = ADD(T4O, T4P);
            T7D = FNMS(KP707106781, T7C, T7B);
            T81 = FMA(KP707106781, T7C, T7B);
            T7F = ADD(T4T, T4U);
            T7G = FNMS(KP707106781, T7F, T7E);
            T82 = FMA(KP707106781, T7F, T7E);
            T7H = SUB(T7D, T7G);
            T83 = SUB(T81, T82);
            T6G = ADD(T3j, T3o);
            T6H = FMA(KP707106781, T6G, T6F);
            T7h = FNMS(KP707106781, T6G, T6F);
            T6N = ADD(T37, T32);
            T6O = FMA(KP707106781, T6N, T6M);
            T7i = FNMS(KP707106781, T6N, T6M);
            T6P = SUB(T6H, T6O);
            T7j = SUB(T7h, T7i);
            {
              E T38, T3p, T4Q, T4V;
              T38 = SUB(T32, T37);
              T39 = FMA(KP707106781, T38, T2X);
              T4p = FNMS(KP707106781, T38, T2X);
              T3p = SUB(T3j, T3o);
              T3q = FNMS(KP707106781, T3p, T3e);
              T4q = FMA(KP707106781, T3p, T3e);
              T3r = ADD(T39, T3q);
              T4r = ADD(T4p, T4q);
              T4Q = SUB(T4O, T4P);
              T4R = FNMS(KP707106781, T4Q, T4N);
              T5l = FMA(KP707106781, T4Q, T4N);
              T4V = SUB(T4T, T4U);
              T4W = FNMS(KP707106781, T4V, T4S);
              T5m = FMA(KP707106781, T4V, T4S);
              T4X = ADD(T4R, T4W);
              T5n = ADD(T5l, T5m);
            }
          }
        }
      }
      {
        E Tca, Tcc, Tp, T1W, Tc5, Tc6, Tcb, Tc7;
        {
          E Tc8, Tc9, T1a, T1V;
          Tc8 = ADD(TbQ, TbP);
          Tc9 = ADD(TbL, TbK);
          Tca = FMA(KP618033988, Tc9, Tc8);
          Tcc = FNMS(KP618033988, Tc8, Tc9);
          Tp = FMA(KP2_000000000, To, T9);
          T1a = ADD(TE, T19);
          T1V = ADD(T1p, T1U);
          T1W = ADD(T1a, T1V);
          Tc5 = FNMS(KP500000000, T1W, Tp);
          Tc6 = SUB(T1a, T1V);
        }
        R0[0] = FMA(KP2_000000000, T1W, Tp);
        Tcb = FNMS(KP1_118033988, Tc6, Tc5);
        R0[WSR(24)] = FNMS(KP1_902113032, Tcc, Tcb);
        R0[WSR(36)] = FMA(KP1_902113032, Tcc, Tcb);
        Tc7 = FMA(KP1_118033988, Tc6, Tc5);
        R0[WSR(48)] = FNMS(KP1_902113032, Tca, Tc7);
        R0[WSR(12)] = FMA(KP1_902113032, Tca, Tc7);
      }
      {
        E TaK, TaM, T6f, T6q, TaB, TaC, TaL, TaD;
        {
          E TaG, TaJ, T6k, T6p;
          TaG = ADD(TaE, TaF);
          TaJ = ADD(TaH, TaI);
          TaK = FMA(KP618033988, TaJ, TaG);
          TaM = FNMS(KP618033988, TaG, TaJ);
          T6f = FNMS(KP2_000000000, T6e, T6d);
          T6k = SUB(T6g, T6j);
          T6p = SUB(T6l, T6o);
          T6q = ADD(T6k, T6p);
          TaB = FNMS(KP500000000, T6q, T6f);
          TaC = SUB(T6k, T6p);
        }
        R0[WSR(15)] = FMA(KP2_000000000, T6q, T6f);
        TaL = FNMS(KP1_118033988, TaC, TaB);
        R0[WSR(39)] = FNMS(KP1_902113032, TaM, TaL);
        R0[WSR(51)] = FMA(KP1_902113032, TaM, TaL);
        TaD = FMA(KP1_118033988, TaC, TaB);
        R0[WSR(3)] = FNMS(KP1_902113032, TaK, TaD);
        R0[WSR(27)] = FMA(KP1_902113032, TaK, TaD);
      }
      {
        E Tay, TaA, T5D, T6c, Tat, Tau, Taz, Tav;
        {
          E Taw, Tax, T5U, T6b;
          Taw = ADD(Ta3, Ta2);
          Tax = ADD(Tae, Tad);
          Tay = FNMS(KP618033988, Tax, Taw);
          TaA = FMA(KP618033988, Taw, Tax);
          T5D = FNMS(KP2_000000000, T5C, T5x);
          T5U = SUB(T5I, T5T);
          T6b = SUB(T5Z, T6a);
          T6c = ADD(T5U, T6b);
          Tat = FNMS(KP500000000, T6c, T5D);
          Tau = SUB(T5U, T6b);
        }
        R0[WSR(45)] = FMA(KP2_000000000, T6c, T5D);
        Taz = FMA(KP1_118033988, Tau, Tat);
        R0[WSR(33)] = FNMS(KP1_902113032, TaA, Taz);
        R0[WSR(57)] = FMA(KP1_902113032, TaA, Taz);
        Tav = FNMS(KP1_118033988, Tau, Tat);
        R0[WSR(9)] = FNMS(KP1_902113032, Tay, Tav);
        R0[WSR(21)] = FMA(KP1_902113032, Tay, Tav);
      }
      {
        E TbE, TbG, T1Z, T2a, Tbz, TbA, TbF, TbB;
        {
          E TbC, TbD, T24, T29;
          TbC = ADD(Tbk, Tbj);
          TbD = ADD(Tbd, Tbc);
          TbE = FNMS(KP618033988, TbD, TbC);
          TbG = FMA(KP618033988, TbC, TbD);
          T1Z = FNMS(KP2_000000000, T1Y, T1X);
          T24 = SUB(T20, T23);
          T29 = SUB(T25, T28);
          T2a = ADD(T24, T29);
          Tbz = FNMS(KP500000000, T2a, T1Z);
          TbA = SUB(T24, T29);
        }
        R0[WSR(30)] = FMA(KP2_000000000, T2a, T1Z);
        TbF = FMA(KP1_118033988, TbA, Tbz);
        R0[WSR(18)] = FNMS(KP1_902113032, TbG, TbF);
        R0[WSR(42)] = FMA(KP1_902113032, TbG, TbF);
        TbB = FNMS(KP1_118033988, TbA, Tbz);
        R0[WSR(54)] = FNMS(KP1_902113032, TbE, TbB);
        R0[WSR(6)] = FMA(KP1_902113032, TbE, TbB);
      }
      {
        E TbO, Tc1, TbT, Tc0, T9D, T9O, TbH, TbI, T9P, T9S, TbX, TbY;
        {
          E TbM, TbN, TbR, TbS;
          TbM = FNMS(KP500000000, TbL, TbK);
          TbN = SUB(T1E, T1T);
          TbO = FNMS(KP866025403, TbN, TbM);
          Tc1 = FMA(KP866025403, TbN, TbM);
          TbR = FNMS(KP500000000, TbQ, TbP);
          TbS = SUB(TT, T18);
          TbT = FNMS(KP866025403, TbS, TbR);
          Tc0 = FMA(KP866025403, TbS, TbR);
        }
        {
          E T9I, T9N, T9Q, T9R;
          T9D = FMA(KP1_732050807, T9C, T9B);
          T9I = FMA(KP1_732050807, T9H, T9E);
          T9N = FMA(KP1_732050807, T9M, T9J);
          T9O = ADD(T9I, T9N);
          TbH = FMA(KP250000000, T9O, T9D);
          TbI = SUB(T9N, T9I);
          T9P = FNMS(KP1_732050807, T9C, T9B);
          T9Q = FNMS(KP1_732050807, T9H, T9E);
          T9R = FNMS(KP1_732050807, T9M, T9J);
          T9S = ADD(T9Q, T9R);
          TbX = FMA(KP250000000, T9S, T9P);
          TbY = SUB(T9R, T9Q);
        }
        {
          E TbJ, TbU, Tc3, Tc4;
          R0[WSR(40)] = SUB(T9D, T9O);
          R0[WSR(20)] = SUB(T9P, T9S);
          TbJ = FNMS(KP559016994, TbI, TbH);
          TbU = FNMS(KP618033988, TbT, TbO);
          R0[WSR(4)] = FNMS(KP1_902113032, TbU, TbJ);
          R0[WSR(16)] = FMA(KP1_902113032, TbU, TbJ);
          Tc3 = FNMS(KP559016994, TbY, TbX);
          Tc4 = FNMS(KP618033988, Tc0, Tc1);
          R0[WSR(44)] = FNMS(KP1_902113032, Tc4, Tc3);
          R0[WSR(56)] = FMA(KP1_902113032, Tc4, Tc3);
          {
            E TbZ, Tc2, TbV, TbW;
            TbZ = FMA(KP559016994, TbY, TbX);
            Tc2 = FMA(KP618033988, Tc1, Tc0);
            R0[WSR(8)] = FNMS(KP1_902113032, Tc2, TbZ);
            R0[WSR(32)] = FMA(KP1_902113032, Tc2, TbZ);
            TbV = FMA(KP559016994, TbI, TbH);
            TbW = FMA(KP618033988, TbO, TbT);
            R0[WSR(28)] = FNMS(KP1_902113032, TbW, TbV);
            R0[WSR(52)] = FMA(KP1_902113032, TbW, TbV);
          }
        }
      }
      {
        E Ta6, Tap, Tah, Tao, T8l, T8M, T9T, T9U, T8N, T8Q, Tal, Tam;
        {
          E Ta4, Ta5, Taf, Tag;
          Ta4 = FNMS(KP500000000, Ta3, Ta2);
          Ta5 = SUB(T69, T64);
          Ta6 = FNMS(KP866025403, Ta5, Ta4);
          Tap = FMA(KP866025403, Ta5, Ta4);
          Taf = FNMS(KP500000000, Tae, Tad);
          Tag = SUB(T5S, T5N);
          Tah = FNMS(KP866025403, Tag, Taf);
          Tao = FMA(KP866025403, Tag, Taf);
        }
        {
          E T8y, T8L, T8O, T8P;
          T8l = FMA(KP1_732050807, T8k, T8f);
          T8y = FNMS(KP1_732050807, T8x, T8m);
          T8L = FNMS(KP1_732050807, T8K, T8z);
          T8M = ADD(T8y, T8L);
          T9T = FNMS(KP250000000, T8M, T8l);
          T9U = SUB(T8y, T8L);
          T8N = FNMS(KP1_732050807, T8k, T8f);
          T8O = FMA(KP1_732050807, T8x, T8m);
          T8P = FMA(KP1_732050807, T8K, T8z);
          T8Q = ADD(T8O, T8P);
          Tal = FNMS(KP250000000, T8Q, T8N);
          Tam = SUB(T8O, T8P);
        }
        {
          E T9V, Tai, Tar, Tas;
          R0[WSR(25)] = ADD(T8l, T8M);
          R0[WSR(5)] = ADD(T8N, T8Q);
          T9V = FNMS(KP559016994, T9U, T9T);
          Tai = FNMS(KP618033988, Tah, Ta6);
          R0[WSR(49)] = FNMS(KP1_902113032, Tai, T9V);
          R0[WSR(1)] = FMA(KP1_902113032, Tai, T9V);
          Tar = FNMS(KP559016994, Tam, Tal);
          Tas = FNMS(KP618033988, Tao, Tap);
          R0[WSR(29)] = FNMS(KP1_902113032, Tas, Tar);
          R0[WSR(41)] = FMA(KP1_902113032, Tas, Tar);
          {
            E Tan, Taq, Taj, Tak;
            Tan = FMA(KP559016994, Tam, Tal);
            Taq = FMA(KP618033988, Tap, Tao);
            R0[WSR(53)] = FNMS(KP1_902113032, Taq, Tan);
            R0[WSR(17)] = FMA(KP1_902113032, Taq, Tan);
            Taj = FMA(KP559016994, T9U, T9T);
            Tak = FMA(KP618033988, Ta6, Tah);
            R0[WSR(13)] = FNMS(KP1_902113032, Tak, Taj);
            R0[WSR(37)] = FMA(KP1_902113032, Tak, Taj);
          }
        }
      }
      {
        E TaS, Tb3, TaV, Tb2, T8T, T94, TaN, TaO, T95, T98, TaZ, Tb0;
        {
          E TaQ, TaR, TaT, TaU;
          TaQ = FNMS(KP500000000, TaE, TaF);
          TaR = SUB(T6i, T6h);
          TaS = FNMS(KP866025403, TaR, TaQ);
          Tb3 = FMA(KP866025403, TaR, TaQ);
          TaT = FNMS(KP500000000, TaH, TaI);
          TaU = SUB(T6n, T6m);
          TaV = FNMS(KP866025403, TaU, TaT);
          Tb2 = FMA(KP866025403, TaU, TaT);
        }
        {
          E T8Y, T93, T96, T97;
          T8T = FMA(KP1_732050807, T8S, T8R);
          T8Y = FNMS(KP1_732050807, T8X, T8U);
          T93 = FNMS(KP1_732050807, T92, T8Z);
          T94 = ADD(T8Y, T93);
          TaN = FNMS(KP250000000, T94, T8T);
          TaO = SUB(T8Y, T93);
          T95 = FNMS(KP1_732050807, T8S, T8R);
          T96 = FMA(KP1_732050807, T8X, T8U);
          T97 = FMA(KP1_732050807, T92, T8Z);
          T98 = ADD(T96, T97);
          TaZ = FNMS(KP250000000, T98, T95);
          Tb0 = SUB(T96, T97);
        }
        {
          E TaP, TaW, Tb5, Tb6;
          R0[WSR(55)] = ADD(T8T, T94);
          R0[WSR(35)] = ADD(T95, T98);
          TaP = FMA(KP559016994, TaO, TaN);
          TaW = FMA(KP618033988, TaV, TaS);
          R0[WSR(43)] = FNMS(KP1_902113032, TaW, TaP);
          R0[WSR(7)] = FMA(KP1_902113032, TaW, TaP);
          Tb5 = FMA(KP559016994, Tb0, TaZ);
          Tb6 = FMA(KP618033988, Tb2, Tb3);
          R0[WSR(23)] = FNMS(KP1_902113032, Tb6, Tb5);
          R0[WSR(47)] = FMA(KP1_902113032, Tb6, Tb5);
          {
            E Tb1, Tb4, TaX, TaY;
            Tb1 = FNMS(KP559016994, Tb0, TaZ);
            Tb4 = FNMS(KP618033988, Tb3, Tb2);
            R0[WSR(59)] = FNMS(KP1_902113032, Tb4, Tb1);
            R0[WSR(11)] = FMA(KP1_902113032, Tb4, Tb1);
            TaX = FNMS(KP559016994, TaO, TaN);
            TaY = FNMS(KP618033988, TaS, TaV);
            R0[WSR(19)] = FNMS(KP1_902113032, TaY, TaX);
            R0[WSR(31)] = FMA(KP1_902113032, TaY, TaX);
          }
        }
      }
      {
        E Tbg, Tbu, Tbn, Tbv, T9d, T9w, Tbr, Tbs, T9x, T9A, Tb7, Tb8;
        {
          E Tbe, Tbf, Tbl, Tbm;
          Tbe = FNMS(KP500000000, Tbd, Tbc);
          Tbf = SUB(T22, T21);
          Tbg = FMA(KP866025403, Tbf, Tbe);
          Tbu = FNMS(KP866025403, Tbf, Tbe);
          Tbl = FNMS(KP500000000, Tbk, Tbj);
          Tbm = SUB(T27, T26);
          Tbn = FMA(KP866025403, Tbm, Tbl);
          Tbv = FNMS(KP866025403, Tbm, Tbl);
        }
        {
          E T9m, T9v, T9y, T9z;
          T9d = FMA(KP1_732050807, T9c, T99);
          T9m = FNMS(KP1_732050807, T9l, T9e);
          T9v = FNMS(KP1_732050807, T9u, T9n);
          T9w = ADD(T9m, T9v);
          Tbr = FNMS(KP250000000, T9w, T9d);
          Tbs = SUB(T9m, T9v);
          T9x = FNMS(KP1_732050807, T9c, T99);
          T9y = FMA(KP1_732050807, T9l, T9e);
          T9z = FMA(KP1_732050807, T9u, T9n);
          T9A = ADD(T9y, T9z);
          Tb7 = FNMS(KP250000000, T9A, T9x);
          Tb8 = SUB(T9y, T9z);
        }
        {
          E Tb9, Tbo, Tbx, Tby;
          R0[WSR(10)] = ADD(T9d, T9w);
          R0[WSR(50)] = ADD(T9x, T9A);
          Tb9 = FMA(KP559016994, Tb8, Tb7);
          Tbo = FMA(KP618033988, Tbn, Tbg);
          R0[WSR(38)] = FNMS(KP1_902113032, Tbo, Tb9);
          R0[WSR(2)] = FMA(KP1_902113032, Tbo, Tb9);
          Tbx = FNMS(KP559016994, Tbs, Tbr);
          Tby = FNMS(KP618033988, Tbu, Tbv);
          R0[WSR(34)] = FNMS(KP1_902113032, Tby, Tbx);
          R0[WSR(46)] = FMA(KP1_902113032, Tby, Tbx);
          {
            E Tbt, Tbw, Tbp, Tbq;
            Tbt = FMA(KP559016994, Tbs, Tbr);
            Tbw = FMA(KP618033988, Tbv, Tbu);
            R0[WSR(58)] = FNMS(KP1_902113032, Tbw, Tbt);
            R0[WSR(22)] = FMA(KP1_902113032, Tbw, Tbt);
            Tbp = FNMS(KP559016994, Tb8, Tb7);
            Tbq = FNMS(KP618033988, Tbg, Tbn);
            R0[WSR(14)] = FNMS(KP1_902113032, Tbq, Tbp);
            R0[WSR(26)] = FMA(KP1_902113032, Tbq, Tbp);
          }
        }
      }
      {
        E T7Z, T8b, Te9, Teo, Teh, Te4, Tep, Teg, T2B, T4k, Tel, Tem,
         T8a, Tee, T8e;
        E TdY;
        {
          E T7X, Te8, Te6, Te7;
          T7X = ADD(T2j, T2A);
          T7Z = FMA(KP1_732050807, T7Y, T7X);
          T8b = FNMS(KP1_732050807, T7Y, T7X);
          Te8 = SUB(T3q, T39);
          Te6 = ADD(T82, T81);
          Te7 = FMA(KP500000000, Te6, Te5);
          Te9 = FMA(KP866025403, Te8, Te7);
          Teo = SUB(Te5, Te6);
          Teh = FNMS(KP866025403, Te8, Te7);
        }
        {
          E Te3, Te1, Te2, T3s, T4j;
          Te3 = SUB(T4h, T40);
          Te1 = SUB(T86, T87);
          Te2 = FNMS(KP500000000, Te1, Te0);
          Te4 = FMA(KP866025403, Te3, Te2);
          Tep = ADD(Te1, Te0);
          Teg = FNMS(KP866025403, Te3, Te2);
          T2B = FNMS(KP2_000000000, T2A, T2j);
          T3s = SUB(T2S, T3r);
          T4j = SUB(T3J, T4i);
          T4k = ADD(T3s, T4j);
          Tel = FNMS(KP500000000, T4k, T2B);
          Tem = SUB(T3s, T4j);
          {
            E T84, T8c, T89, T8d, T80, T85;
            T80 = FMA(KP2_000000000, T2S, T3r);
            T84 = FNMS(KP1_732050807, T83, T80);
            T8c = FMA(KP1_732050807, T83, T80);
            T85 = FMA(KP2_000000000, T3J, T4i);
            T89 = FNMS(KP1_732050807, T88, T85);
            T8d = FMA(KP1_732050807, T88, T85);
            T8a = ADD(T84, T89);
            Tee = SUB(T84, T89);
            T8e = ADD(T8c, T8d);
            TdY = SUB(T8c, T8d);
          }
        }
        R1[WSR(7)] = FMA(KP2_000000000, T4k, T2B);
        R1[WSR(47)] = ADD(T7Z, T8a);
        R1[WSR(27)] = ADD(T8b, T8e);
        {
          E Ter, Tes, Ten, Teq;
          Ter = FNMS(KP1_118033988, Tem, Tel);
          Tes = FNMS(KP618033988, Teo, Tep);
          R1[WSR(31)] = FNMS(KP1_902113032, Tes, Ter);
          R1[WSR(43)] = FMA(KP1_902113032, Tes, Ter);
          Ten = FMA(KP1_118033988, Tem, Tel);
          Teq = FMA(KP618033988, Tep, Teo);
          R1[WSR(55)] = FNMS(KP1_902113032, Teq, Ten);
          R1[WSR(19)] = FMA(KP1_902113032, Teq, Ten);
        }
        {
          E Tei, Tek, Tef, Tej, Ted;
          Tei = FNMS(KP618033988, Teh, Teg);
          Tek = FMA(KP618033988, Teg, Teh);
          Ted = FNMS(KP250000000, T8a, T7Z);
          Tef = FNMS(KP559016994, Tee, Ted);
          Tej = FMA(KP559016994, Tee, Ted);
          R1[WSR(11)] = FNMS(KP1_902113032, Tei, Tef);
          R1[WSR(59)] = FMA(KP1_902113032, Tek, Tej);
          R1[WSR(23)] = FMA(KP1_902113032, Tei, Tef);
          R1[WSR(35)] = FNMS(KP1_902113032, Tek, Tej);
        }
        {
          E Tea, Tec, TdZ, Teb, TdX;
          Tea = FNMS(KP618033988, Te9, Te4);
          Tec = FMA(KP618033988, Te4, Te9);
          TdX = FNMS(KP250000000, T8e, T8b);
          TdZ = FNMS(KP559016994, TdY, TdX);
          Teb = FMA(KP559016994, TdY, TdX);
          R1[WSR(51)] = FNMS(KP1_902113032, Tea, TdZ);
          R1[WSR(39)] = FMA(KP1_902113032, Tec, Teb);
          R1[WSR(3)] = FMA(KP1_902113032, Tea, TdZ);
          R1[WSR(15)] = FNMS(KP1_902113032, Tec, Teb);
        }
      }
      {
        E T6z, T79, Tcx, TcN, TcE, Tco, TcM, TcF, T4H, T5g, TcJ, TcK,
         T78, TcC, T7c;
        E Tce;
        {
          E T6r, Tcw, Tcu, Tcv;
          T6r = ADD(T4B, T4G);
          T6z = FMA(KP1_732050807, T6y, T6r);
          T79 = FNMS(KP1_732050807, T6y, T6r);
          Tcw = SUB(T5d, T58);
          Tcu = ADD(T6Y, T75);
          Tcv = FNMS(KP500000000, Tcu, Tct);
          Tcx = FMA(KP866025403, Tcw, Tcv);
          TcN = ADD(Tcu, Tct);
          TcE = FNMS(KP866025403, Tcw, Tcv);
        }
        {
          E Tcn, Tcl, Tcm, T4Y, T5f;
          Tcn = SUB(T4W, T4R);
          Tcl = ADD(T6H, T6O);
          Tcm = FNMS(KP500000000, Tcl, Tck);
          Tco = FMA(KP866025403, Tcn, Tcm);
          TcM = ADD(Tcl, Tck);
          TcF = FNMS(KP866025403, Tcn, Tcm);
          T4H = FNMS(KP2_000000000, T4G, T4B);
          T4Y = SUB(T4M, T4X);
          T5f = SUB(T53, T5e);
          T5g = ADD(T4Y, T5f);
          TcJ = FNMS(KP500000000, T5g, T4H);
          TcK = SUB(T4Y, T5f);
          {
            E T6Q, T7a, T77, T7b, T6A, T6R;
            T6A = FMA(KP2_000000000, T4M, T4X);
            T6Q = FNMS(KP1_732050807, T6P, T6A);
            T7a = FMA(KP1_732050807, T6P, T6A);
            T6R = FMA(KP2_000000000, T53, T5e);
            T77 = FNMS(KP1_732050807, T76, T6R);
            T7b = FMA(KP1_732050807, T76, T6R);
            T78 = ADD(T6Q, T77);
            TcC = SUB(T6Q, T77);
            T7c = ADD(T7a, T7b);
            Tce = SUB(T7a, T7b);
          }
        }
        R1[WSR(52)] = FMA(KP2_000000000, T5g, T4H);
        R1[WSR(32)] = ADD(T6z, T78);
        R1[WSR(12)] = ADD(T79, T7c);
        {
          E TcP, TcQ, TcL, TcO;
          TcP = FNMS(KP1_118033988, TcK, TcJ);
          TcQ = FNMS(KP618033988, TcM, TcN);
          R1[WSR(16)] = FNMS(KP1_902113032, TcQ, TcP);
          R1[WSR(28)] = FMA(KP1_902113032, TcQ, TcP);
          TcL = FMA(KP1_118033988, TcK, TcJ);
          TcO = FMA(KP618033988, TcN, TcM);
          R1[WSR(40)] = FNMS(KP1_902113032, TcO, TcL);
          R1[WSR(4)] = FMA(KP1_902113032, TcO, TcL);
        }
        {
          E TcG, TcI, TcD, TcH, TcB;
          TcG = FNMS(KP618033988, TcF, TcE);
          TcI = FMA(KP618033988, TcE, TcF);
          TcB = FNMS(KP250000000, T78, T6z);
          TcD = FNMS(KP559016994, TcC, TcB);
          TcH = FMA(KP559016994, TcC, TcB);
          R1[WSR(56)] = FNMS(KP1_902113032, TcG, TcD);
          R1[WSR(44)] = FMA(KP1_902113032, TcI, TcH);
          R1[WSR(8)] = FMA(KP1_902113032, TcG, TcD);
          R1[WSR(20)] = FNMS(KP1_902113032, TcI, TcH);
        }
        {
          E Tcy, TcA, Tcf, Tcz, Tcd;
          Tcy = FMA(KP618033988, Tcx, Tco);
          TcA = FNMS(KP618033988, Tco, Tcx);
          Tcd = FNMS(KP250000000, T7c, T79);
          Tcf = FMA(KP559016994, Tce, Tcd);
          Tcz = FNMS(KP559016994, Tce, Tcd);
          R1[0] = FNMS(KP1_902113032, Tcy, Tcf);
          R1[WSR(48)] = FMA(KP1_902113032, TcA, Tcz);
          R1[WSR(24)] = FMA(KP1_902113032, Tcy, Tcf);
          R1[WSR(36)] = FNMS(KP1_902113032, TcA, Tcz);
        }
      }
      {
        E T7z, T7T, Tdz, TdS, TdI, Tdu, TdT, TdL, T4n, T4y, Tdn, Tdo,
         T7S, TdQ, T7W;
        E TdE;
        {
          E T7v, TdH, Tdy, TdG;
          T7v = ADD(T4l, T4m);
          T7z = FMA(KP1_732050807, T7y, T7v);
          T7T = FNMS(KP1_732050807, T7y, T7v);
          TdH = SUB(T4q, T4p);
          Tdy = ADD(T7G, T7D);
          TdG = FMA(KP500000000, Tdy, Tdx);
          Tdz = SUB(Tdx, Tdy);
          TdS = FMA(KP866025403, TdH, TdG);
          TdI = FNMS(KP866025403, TdH, TdG);
        }
        {
          E TdK, Tdq, TdJ, T4s, T4x;
          TdK = SUB(T4v, T4u);
          Tdq = SUB(T7M, T7P);
          TdJ = FNMS(KP500000000, Tdq, Tdt);
          Tdu = ADD(Tdq, Tdt);
          TdT = FMA(KP866025403, TdK, TdJ);
          TdL = FNMS(KP866025403, TdK, TdJ);
          T4n = FNMS(KP2_000000000, T4m, T4l);
          T4s = SUB(T4o, T4r);
          T4x = SUB(T4t, T4w);
          T4y = ADD(T4s, T4x);
          Tdn = FNMS(KP500000000, T4y, T4n);
          Tdo = SUB(T4s, T4x);
          {
            E T7I, T7U, T7R, T7V, T7A, T7J;
            T7A = FMA(KP2_000000000, T4o, T4r);
            T7I = FNMS(KP1_732050807, T7H, T7A);
            T7U = FMA(KP1_732050807, T7H, T7A);
            T7J = FMA(KP2_000000000, T4t, T4w);
            T7R = FNMS(KP1_732050807, T7Q, T7J);
            T7V = FMA(KP1_732050807, T7Q, T7J);
            T7S = ADD(T7I, T7R);
            TdQ = SUB(T7U, T7V);
            T7W = ADD(T7U, T7V);
            TdE = SUB(T7I, T7R);
          }
        }
        R1[WSR(37)] = FMA(KP2_000000000, T4y, T4n);
        R1[WSR(17)] = ADD(T7z, T7S);
        R1[WSR(57)] = ADD(T7T, T7W);
        {
          E TdB, TdC, Tdp, TdA;
          TdB = FMA(KP1_118033988, Tdo, Tdn);
          TdC = FMA(KP618033988, Tdu, Tdz);
          R1[WSR(25)] = FNMS(KP1_902113032, TdC, TdB);
          R1[WSR(49)] = FMA(KP1_902113032, TdC, TdB);
          Tdp = FNMS(KP1_118033988, Tdo, Tdn);
          TdA = FNMS(KP618033988, Tdz, Tdu);
          R1[WSR(1)] = FNMS(KP1_902113032, TdA, Tdp);
          R1[WSR(13)] = FMA(KP1_902113032, TdA, Tdp);
        }
        {
          E TdU, TdW, TdR, TdV, TdP;
          TdU = FMA(KP618033988, TdT, TdS);
          TdW = FNMS(KP618033988, TdS, TdT);
          TdP = FNMS(KP250000000, T7W, T7T);
          TdR = FMA(KP559016994, TdQ, TdP);
          TdV = FNMS(KP559016994, TdQ, TdP);
          R1[WSR(45)] = FNMS(KP1_902113032, TdU, TdR);
          R1[WSR(33)] = FMA(KP1_902113032, TdW, TdV);
          R1[WSR(9)] = FMA(KP1_902113032, TdU, TdR);
          R1[WSR(21)] = FNMS(KP1_902113032, TdW, TdV);
        }
        {
          E TdM, TdO, TdF, TdN, TdD;
          TdM = FMA(KP618033988, TdL, TdI);
          TdO = FNMS(KP618033988, TdI, TdL);
          TdD = FNMS(KP250000000, T7S, T7z);
          TdF = FMA(KP559016994, TdE, TdD);
          TdN = FNMS(KP559016994, TdE, TdD);
          R1[WSR(5)] = FNMS(KP1_902113032, TdM, TdF);
          R1[WSR(53)] = FMA(KP1_902113032, TdO, TdN);
          R1[WSR(29)] = FMA(KP1_902113032, TdM, TdF);
          R1[WSR(41)] = FNMS(KP1_902113032, TdO, TdN);
        }
      }
      {
        E T7f, T7r, Td3, Tdi, Tda, TcY, Tdj, Tdb, T5j, T5u, Tdf, Tdg,
         T7q, Td8, T7u;
        E TcS;
        {
          E T7d, Td2, Td0, Td1;
          T7d = ADD(T5h, T5i);
          T7f = FMA(KP1_732050807, T7e, T7d);
          T7r = FNMS(KP1_732050807, T7e, T7d);
          Td2 = SUB(T5m, T5l);
          Td0 = ADD(T7h, T7i);
          Td1 = FNMS(KP500000000, Td0, TcZ);
          Td3 = FMA(KP866025403, Td2, Td1);
          Tdi = ADD(Td0, TcZ);
          Tda = FNMS(KP866025403, Td2, Td1);
        }
        {
          E TcX, TcV, TcW, T5o, T5t;
          TcX = SUB(T5r, T5q);
          TcV = ADD(T7m, T7n);
          TcW = FNMS(KP500000000, TcV, TcU);
          TcY = FMA(KP866025403, TcX, TcW);
          Tdj = ADD(TcV, TcU);
          Tdb = FNMS(KP866025403, TcX, TcW);
          T5j = FNMS(KP2_000000000, T5i, T5h);
          T5o = SUB(T5k, T5n);
          T5t = SUB(T5p, T5s);
          T5u = ADD(T5o, T5t);
          Tdf = FNMS(KP500000000, T5u, T5j);
          Tdg = SUB(T5o, T5t);
          {
            E T7k, T7s, T7p, T7t, T7g, T7l;
            T7g = FMA(KP2_000000000, T5k, T5n);
            T7k = FNMS(KP1_732050807, T7j, T7g);
            T7s = FMA(KP1_732050807, T7j, T7g);
            T7l = FMA(KP2_000000000, T5p, T5s);
            T7p = FNMS(KP1_732050807, T7o, T7l);
            T7t = FMA(KP1_732050807, T7o, T7l);
            T7q = ADD(T7k, T7p);
            Td8 = SUB(T7k, T7p);
            T7u = ADD(T7s, T7t);
            TcS = SUB(T7s, T7t);
          }
        }
        R1[WSR(22)] = FMA(KP2_000000000, T5u, T5j);
        R1[WSR(2)] = ADD(T7f, T7q);
        R1[WSR(42)] = ADD(T7r, T7u);
        {
          E Tdl, Tdm, Tdh, Tdk;
          Tdl = FNMS(KP1_118033988, Tdg, Tdf);
          Tdm = FNMS(KP618033988, Tdi, Tdj);
          R1[WSR(46)] = FNMS(KP1_902113032, Tdm, Tdl);
          R1[WSR(58)] = FMA(KP1_902113032, Tdm, Tdl);
          Tdh = FMA(KP1_118033988, Tdg, Tdf);
          Tdk = FMA(KP618033988, Tdj, Tdi);
          R1[WSR(10)] = FNMS(KP1_902113032, Tdk, Tdh);
          R1[WSR(34)] = FMA(KP1_902113032, Tdk, Tdh);
        }
        {
          E Tdc, Tde, Td9, Tdd, Td7;
          Tdc = FMA(KP618033988, Tdb, Tda);
          Tde = FNMS(KP618033988, Tda, Tdb);
          Td7 = FNMS(KP250000000, T7q, T7f);
          Td9 = FMA(KP559016994, Td8, Td7);
          Tdd = FNMS(KP559016994, Td8, Td7);
          R1[WSR(50)] = FNMS(KP1_902113032, Tdc, Td9);
          R1[WSR(38)] = FMA(KP1_902113032, Tde, Tdd);
          R1[WSR(14)] = FMA(KP1_902113032, Tdc, Td9);
          R1[WSR(26)] = FNMS(KP1_902113032, Tde, Tdd);
        }
        {
          E Td4, Td6, TcT, Td5, TcR;
          Td4 = FNMS(KP618033988, Td3, TcY);
          Td6 = FMA(KP618033988, TcY, Td3);
          TcR = FNMS(KP250000000, T7u, T7r);
          TcT = FNMS(KP559016994, TcS, TcR);
          Td5 = FMA(KP559016994, TcS, TcR);
          R1[WSR(6)] = FNMS(KP1_902113032, Td4, TcT);
          R1[WSR(54)] = FMA(KP1_902113032, Td6, Td5);
          R1[WSR(18)] = FMA(KP1_902113032, Td4, TcT);
          R1[WSR(30)] = FNMS(KP1_902113032, Td6, Td5);
        }
      }
    }
  }
}
