/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 4 -standalone -fma -generic-arith -compact -name dft_codelet_r2hc_4 */

/*
 * This function contains 6 FP additions, 0 FP multiplications,
 * (or, 6 additions, 0 multiplications, 0 fused multiply/add),
 * 7 stack variables, 0 constants, and 8 memory accesses
 */
void dft_codelet_r2hc_4(const R * R0, const R * R1, R * Cr, R * Ci)
{
  {
    
    {
      E T1, T2, T3, T4, T5, T6;
      T1 = R0[0];
      T2 = R0[WSR(1)];
      T3 = ADD(T1, T2);
      T4 = R1[0];
      T5 = R1[WSR(1)];
      T6 = ADD(T4, T5);
      Cr[WSCR(1)] = SUB(T1, T2);
      Ci[WSCI(1)] = SUB(T5, T4);
      Cr[WSCR(2)] = SUB(T3, T6);
      Cr[0] = ADD(T3, T6);
    }
  }
}
