/*

   calin/math/rng_gaussian_ziggurat.cpp -- Stephen Fegan -- 2022-09-25

   Constants for Gaussian Ziggurat - generated by python notebook
   ~/Google Drive/calin/Ziggurat - Gaussian.ipynb

   Copyright 2022, Stephen Fegan <sfegan@llr.in2p3.fr>
   Laboratoire Leprince-Ringuet, CNRS/IN2P3, Ecole Polytechnique, Institut Polytechnique de Paris

   This file is part of "calin"

   "calin" is free software: you can redistribute it and/or modify it
   under the terms of the GNU General Public License version 2 or
   later, as published by the Free Software Foundation.

   "calin" is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

*/

#include <stdint.h>
#include <math/rng.hpp>

#define ZIGGURAT_TYPE float

namespace calin { namespace math { namespace rng { namespace gaussian_ziggurat_float {

#include "rng_gaussian_ziggurat.inc"

} } } } // namespace calin::math::rng::gaussian_ziggurat_float